### ISSUE TITLE
replacement of < and > with &lt; and &gt;

### ISSUE THREAD

**Issue by amper5and** [janl/mustache.js#110]
Some of my data objects use ready HTML with regular tags surrounded by "<" and ">" . Mustache.js converts these to `&lt;` and `&gt;`. Doing a `String.replace(/&gt;/g,'>').replace(/&lt;/g,'<')` on the resultant output introduces a lot of lag. 

Is this is expected behavior? Can it be changed to preserve the <'s and >'s? Should these symbols be escaped somehow?

**Comment by githubwangxu** [comment]
that cool👍！！！
