### ISSUE TITLE
Byte Order Mark as whitespace in regexp

### ISSUE THREAD

**Issue by subzey** [janl/mustache.js#163]
`trim` function uses regular expression `/\s+/` in order to get all whitespace chars.
There may be a hidden trouble due to the fact ECMA 262-5 marks BOM character (0xFEFF) as whitespace, while ECMA 262-3 doesn't.

For example, `'\ufeff   fooo'` will be trimmed in most modern browsers, and will not be trimmed in Node.js

**Comment by dasilvacontin** [comment]
Closed via e54aca8e3b054a769f5ab4fc295885be6b4b071a.
