### ISSUE TITLE
Unescape all values

### ISSUE THREAD

**Issue by ForbesLindesay** [janl/mustache.js#244]
would it be possible to add an option to not do any escaping of html at all?

**Comment by NishadKumar** [comment]
> I haven't tested it, but according to the man page:
> `All variables are HTML escaped by default. If you want to return unescaped HTML, use the triple mustache: {{{name}}}.`
> If that doesn't work you could use a function which simply returns it's input unescaped.

Thanks a ton!! This works.

**Comment by wll8** [comment]
Using `{{{` is null and void in this case:

``` js
template = `@{emoji}@{text}`
view = {
  text: "http://test.com",
  emoji: "✨",
}
mustache.render(template, view, {}, [`@{`, `}`])
```

**Comment by lordbyron** [comment]
@wll8 perhaps what you're looking for, at least in the version i've seen, is `@{&text}`. the `&` symbol tells it not to do any escaping
