### ISSUE TITLE
Clear Partial Cache

### ISSUE THREAD

**Issue by ajacksified** [janl/mustache.js#275]
I'm working with mustache files such that I have a layout file, and multiple content files; the layout file has the css, header, footer, etc, and the content is bare content. It looks something like this:

layout.mustache

```
<html>
....
<body>
<h1>site</h1>
{{> content }}
....
</html>
```

page1.msutache

```
<h1>this is my page 1</h1>
```

page2.msutache

```
<h1>this is my page 2</h1>
```

When rendering, I pass in a partial named content with the content of one of these pages. However, mustache.js aggressively caches partials by name; so when I switch from page 1 to page 2, I still see page 1's content (because they're both partials "named" content.)

I've solved this by adding a clearPartialCache method to Writer and exposing that through Mustache, but it feels kind of hacky. I'm interested in alternatives to fix this; a noPartialCache flag in config, or in render, maybe? Or maybe this works.

I want to avoid using hogan.js's inverse-partials to build layouts; I did this at first, but they're tricky to share between the client and the server. I don't want the client re-rendering the header and everything on each page change, and I'd rather stick to Mustache spec if possible anyway.

Thoughts?

**Comment by lcsqlpete** [comment]
I know this is an old issue but it doesn't seem to have been fully fixed. I am in development mode on a project using Mustache/js with several partials.  Every time I make a change to the partial I'm working on and copy it over to my test server, the previous version of the partial is used when I run the application.  The only way I am able to continue development is to change the name of the partial file and refer to the new name in the javascript that processes it.
