### ISSUE TITLE
Wrong this context in sub objects

### ISSUE THREAD

**Issue by compojoom** [janl/mustache.js#293]
Hey guys,
I'm not big fan of partials. I actually prefer to merge my objects into 1 and pass it to my template. Now this works well when the objects are really simple -> just returning values. But if you have a function that calls another function, then things tend to brake, because we are not in the correct context. 
Here is an example:
http://jsfiddle.net/BjvPt/70/

As you can see I have added a new test property to my data object. 
Because of that when I call the render I get an error that this.get is not a function. It is not a function because on this line - we just pass the global object.
https://github.com/janl/mustache.js/blob/master/mustache.js#L172

Changing line 172 to this:

		if (typeof value === 'function') {
			var view = this.view;
			if (name.indexOf('.') > 0){
				var objects = name.split('.');
    // remove the last element of the array as it is the function name
				objects.pop();
				if(objects.length) {
					i = 0;
					while (view && i < objects.length){
						view = view[objects[i++]];
					}
				}
			}
			value = value.call(view);
		}

We can ensure that we pass the correct "this" object to the call function. Now this works pretty well on my test installation. I don't see any side effects and the question is -> is what I did correct and is there a specific reason why we pass this.view instead of the specific view in question? Should I submit a pull request for this?

**Comment by dasilvacontin** [comment]
Not sure why you complicated the example – here's a simple version (if I understood correctly):
```js
➜  temp  cat wrong_context.js
var Mustache = require('mustache')

var view = {
  name: 'foo',
  data: {
    name: 'bar',
    getName: function () {
      return this.name
    }
  }
}

art = Mustache.render('{{ data.getName }}\n{{#data}}{{ getName }}{{/data}}', view)
console.log(art)

➜  temp  node wrong_context.js
foo
bar
```

**Comment by dasilvacontin** [comment]
Food for thought:
```js
➜  temp  cat upper_context.js
var Mustache = require('mustache')

var view = {
  data: {
    name: 'John'
  },
  getName: function () {
    return this.name
  }
}

var art = Mustache.render('{{#data}}{{ getName }}{{/data}}', view)
console.log(art)

➜  temp  node upper_context.js
John
```

**Comment by dasilvacontin** [comment]
I think behaviour is correct – it would be hard to create helpers if their implicit parameter (`this`) was always their local scope. If that's the behaviour you are looking for in a function, you can always use `bind`.

**Comment by dasilvacontin** [comment]
Okay, I didn't read properly. You mentioned `global` being passed in, and that was fixed/improved long ago.

**Comment by compojoom** [comment]
The truth is that I no longer remember what I was doing and why. This was 2 years ago...
Cheers.
