### ISSUE TITLE
Added options object to the render function

### ISSUE THREAD

**Issue by gbrian** [janl/mustache.js#328]
I've made a basic change in your code to allow pass an options object to the render function, basically to disable the "escape" call when rendering values, because i use a lot of nested html to generate more html and i found this way easily than hacking the render function.

I've added a new "options" optional parameter to the "render" call.

``` js
mustache.render = function (template, view, partials, options) {
    return defaultWriter.render(template, view, partials, options || mustache.options/*Def*/);
  }
```

On the definition:

``` js
(function (root, factory) {
  if (typeof exports === "object" && exports) {
    factory(exports); // CommonJS
  } else {
    var mustache = {
        options:{
            escape: true
        }
    };
    factory(mustache);
    if (typeof define === "function" && define.amd) {
      define(mustache); // AMD
    } else {
      root.Mustache = mustache; // <script>
    }
  }
}(this, function (mustache) {
```

And propagate it until 
function renderTokens(tokens, writer, context, template, options) 

where i used 

``` js
...
if (value != null) buffer += options.escape ? mustache.escape(value): value;
...
```

**Comment by raine** [comment]
The solution provided above is not optimal at all.

What if you want to have escaping in some calls, and not in others?

You'd have to keep track of the original escaping function, and assign it back to `mustache.escape` whenever done rendering. Mutate global state to have side effects in function calls. Not a good API.

Correct way is to have it as parameter to `mustache.render`.
