### ISSUE TITLE
Dot notation for object keys with dots in the name

### ISSUE THREAD

**Issue by ghost** [janl/mustache.js#343]
It would be really handy for me, and maybe others† if this could be supported.  A backend database library I use supports this notation so I end up with objects like this:

```
{
  abc: { 'something.with.dots': 42 }
}
```

I wish I could do something like this in Mustache:

```
{{abc.somehting\.with\.dots}}
```

or

```
{{abc[something.with.dots]}}
```

It's not that hard to work around, but I thought I'd throw it out there.

† http://stackoverflow.com/questions/14901683/how-do-i-reference-a-field-name-that-contains-a-dot-in-mustache-template

**Comment by alaamebrahim** [comment]
you can replace dots with "" before you deserialize your json
so the code should actually look like this
`{
  abc: { 'somethingwithdots': 42 }
}`

**Comment by newasmod** [comment]
Dudes, please help! i have object key properties with dots in name. I need to set nested properties, it doesnot work. set(object, 'a.b.c.d',12345) sets obj = {a: {b: {c:{d:12345}}}} , 
but i need obj = {'a.b.c.d' : 12345}

**Comment by allenrowland** [comment]
You should be able to call it like this: obj['a.b.c.d'];

**Comment by DanielUranga** [comment]
Was affected by this bug, been able to workaround but would be very good to see it fixed.

**Comment by FabricioJardin** [comment]
@DanielUranga yah :'(

**Comment by FabricioJardin** [comment]
I solved with the dot-object lib (https://github.com/rhalff/dot-object) before passing my obj with values to render:

import * as dot from 'dot-object'
import * as Mustache from 'mustache'

const vars = dot.object({
    "PRODUCT.TITLE": "All Star Test",
    "PRODUCT.BRAND": "Converse All Star",
})

Mustache.render("{{PRODUCT.TITLE}} - {{PRODUCT.BRAND}}", obj)

**Comment by charlysotelo** [comment]
Was affected by this. 

Escaping characters is basic behavior guys... How is this not supported?

**Comment by anlesk** [comment]
Yeah, sadly, I've faced that as well.

**Comment by mnmami** [comment]
Is this still not considered?

**Comment by ThorbenJ** [comment]
I know this is closed, but I still wish dedotting was not necessary. If escaping is not the way, what about quoting?
e.g. `{{{ a."b.c".d }}}`
Or allow a custom tokeniser that takes a string and passes back an array.
e.g. the current implementation would be:
```
M = require("mustache")
M.tokenise_path = function (path) {
    return path.split('.')
}
```

However advanced users could provide their own tokenisers and decide for themselves how to handle various characters.

FYI for anyone else, this is currently what I do:
```
    function deDot (obj) {
        for (var k in obj) {
            if (k.indexOf('.')>0) {
                var nk = k.replaceAll('.', '~')
                delete Object.assign(obj, {[nk]: obj[k] })[k]
            }
            if (obj[k] instanceof Object) {
                deDot(obj[k])
            }
        }
    }
```
