### ISSUE TITLE
Inappropriate Context of This

### ISSUE THREAD

**Issue by codeviking** [janl/mustache.js#363]
Let me preface this with the fact that this may not actually be an issue, as it may instead be an inappropriate use of mustache.  If so, don't hesitate to point me in the right direction.

It appears as though when executing a function from the mustache context, the context of `this` is incorrect if executing a function on an object that is a child property of the parent template data.  

That's a mouthful, so here's a (simplified) code sample:

Template
```
{{#user.hasName}}
    <strong>{{user.name}}</strong>
{{/user.hasName}}
```

```
var User = function(name) {
   this.name = name;
};

User.prototype.hasName = function() {
  return typeof this.name !== 'undefined';
};

Mustache.render(
   template,
   {
       user: new User("Sam")
    }
);
```

In the above example, `hasName` will return `false`, when executed from the mustache context, as `this` when executing `hasName` will be set to the parent object instance (which doesn't have a `name` property).

Make sense?  Am I totally misusing things here?

To me it seems like a bug in the logic that is executing functions.  If you're executing a method on a property, the context of `this` in that function should be the object on which the method is being executed, rather than the parent object.

**Comment by dasilvacontin** [comment]
I actually believe behaviour is correct for the reasons I left at #293.
