### ISSUE TITLE
Prevent replacing if the field is undefined

### ISSUE THREAD

**Issue by IonicaBizau** [janl/mustache.js#383]
How can I prevent replacing if the field is undefined?

``` js
> require("mustache").render("{{{hi}}}", {})
''
```

**Comment by IonicaBizau** [comment]
Recently, I released [`barbe`](https://github.com/IonicaBizau/barbe), which handles this issue. It's just a replacing thingie.

Maybe it is useful to someone. :dizzy:

**Comment by dasilvacontin** [comment]
I wasn't around here back when this issue was created.

Just fyi, some simple modifications in `Context.lookup` could add that feature, we just need to check if we've hit a value during the lookup (we can't check for undefined/null since it's a valid value for a key).
