### ISSUE TITLE
Looking up in parent context on foo: null is contrary to RFC

### ISSUE THREAD

**Issue by Roman600** [janl/mustache.js#397]
Mustache RFC:
>Variables
The most basic tag type is the variable. A {{name}} tag in a basic template will try to find the name key in the current context. If there is <b>no name key</b>, the parent contexts will be checked recursively. If the top context is reached and the name key is still not found, nothing will be rendered.

But <b>I do have</b> a property in children object and it's value is <b>null</b> (which is false in some way). And I expect nothing to be rendered, but instead mustache.js looks up for a value in parent context and finds it, and shows it. But it's parent's value, not children's. And children <b>has it's own value</b>, and it's null. So according to RFC looking up doesn't need to be done.

The same thing happens not with only variables {{key}}, but with sections {{#key}}{{/key}} too.

**Comment by phillipj** [comment]
Fixed in a020430

**Comment by dasilvacontin** [comment]
Oh, that commit is from when I believed writing 'fixes' once before a bunch of issue numbers was enough. :smile:
