### ISSUE TITLE
number rendered as [object Object]

### ISSUE THREAD

**Issue by coolaj86** [janl/mustache.js#415]
I'm using Mustache `"mustache": "~0.8.2"` via bower in Chrome `Version 39.0.2171.95 (64-bit)`

I have this in my template

```html
  {{# data.author.twitter_id }}
    <meta name="twitter:site:id" content="{{ . }}">
  {{/ data.author.twitter_id }}
```

and this is my data

```javascript
{ data: { author: { twitter_id: 15191378 } } }
```

So this is literally run as

```javascript
output = Mustache.render(
  '  {{# data.author.twitter_id }}\n   <meta name="twitter:site:id" content="{{ . }}">\n   {{/ data.author.twitter_id }}'
, { data: { author: { twitter_id: 15191378 } } }
);
```

And literally gets this output:

```html
<meta name="twitter:site:id" content="[object Object]">
```

What!?!?!?!?!

Any ideas?

Now, I can converts numbers to strings before passing them to Mustache, but that may actually turn out to have a lot of hard-to-catch cases in my application. I'd imagine this is a fairly simple type check fix somewhere in the bowels of the Mustache code?

**Comment by bobthecow** [comment]
It's something to do with the implicit iterator tag (`{{ . }}`). This template does what you'd expect:

```html+jinja
{{# data.author }}
    <meta name="twitter:site:id" content="{{ twitter_id }}">
{{/ data.author }}
```

I don't know where to fix it, but hopefully that helps someone narrow it down :)

**Comment by dasilvacontin** [comment]
I see, interesting bug. I wonder if fixing this will break other test cases.

**Comment by rndme** [comment]
expanding renderTokens with number handling seems to fix it: `  } else if (typeof value === 'object' || typeof value === 'string'|| typeof value === 'number') {`

**Comment by phillipj** [comment]
Spot on @rndme :+1: I just opened a pull request with the fix you proposed
