### ISSUE TITLE
git --tag v1.0.0 for bower

### ISSUE THREAD

**Issue by coolaj86** [janl/mustache.js#416]
you've updated the bower.json, but haven't added the git tag, so the latest is not available on bower.

**Comment by dasilvacontin** [comment]
@coolaj86, thanks for the heads up, I haven't really used bower that much. I'll get around it now.

**Comment by dasilvacontin** [comment]
It should be solved now. I was able to download 1.0.0 from bower myself. Thanks for reporting the issue!
