### ISSUE TITLE
Using multiple sections fails

### ISSUE THREAD

**Issue by marcelboettcher** [janl/mustache.js#417]
Hey, 
could you tell me why this is not working? I'm getting an error that the last {{render}} section is not closed properly. What am I confusing here?
render is the computed value: true
even using render and render2 does not help.

```
{{#render}}
 Test 1
{{/render}}

Render always.

{{#render}}
 Test 2
{{/render}}

```

**Comment by bobthecow** [comment]
Those aren't sections. Sections start with `#` :)

```html+jinja
{{#render}}
  Test 1
{{/render}}
```

**Comment by marcelboettcher** [comment]
sorry my fault, but I mean # :)

**Comment by bobthecow** [comment]
Then that should work:

![render-true](https://cloud.githubusercontent.com/assets/53660/5665497/b3397b8a-970d-11e4-8704-8456a3adc2d2.png)

**Comment by marcelboettcher** [comment]
hmm, but is does not in my case. Real code is a svg and looks like this:

```
{{#render}}
<g clip-path="url(#{{clippingId}})">
{{/render}}
	<image id="{{id}}"
		xlink:href="{{src}}"
		x="{{image.x}}" y="{{image.y}}" 
		width="{{image.width}}" height="{{image.height}}"
		transform="rotate({{image.rotation}}, {{image.getCenter().x}}, {{image.getCenter().y}})"
		preserveAspectRatio="none" />
{{#render}}
</g>
{{/render}}
```

Using 0.6.1

**Comment by bobthecow** [comment]
are you using mustache.js? i didn't think there was a 0.6.1.

anyway, the current version is at least 8 versions newer (1.0.0), so maybe update it and see if that fixes your problem?

**Comment by marcelboettcher** [comment]
sorry, using ractive.js in that version, but they use mustache.js
maybe I need to ask them. Thanks for your support!

**Comment by dasilvacontin** [comment]
Ractive.js doesn't really seem to use mustache.js: https://github.com/ractivejs/ractive/tree/dev/src/virtualdom/items/shared/Mustache

**Comment by marcelboettcher** [comment]
At least the say to on their homepage: "It takes your Mustache templates and transforms them into a lightweight representation of the DOM"

But I haven't looked deeper into the code.

**Comment by bobthecow** [comment]
I read that as "Ractive is a mustache implementation", not "Ractive uses mustache.js". There are plenty of mustache implementations :)

**Comment by marcelboettcher** [comment]
ah, got it, thanks!
