### ISSUE TITLE
Mustache templating  with  array of array object.

### ISSUE THREAD

**Issue by daghera** [janl/mustache.js#419]
I have problem to display  object which is in array of array like the following:
{
  "employees": [0] ["Developer"] [
    {"firstName": "John", "lastName": "Smith"}]
   [1]["Developer"][
    {"firstName": "John","lastName":"Doe"}]
   [2]["Tester"][
   {"firstName":"Jane","lastName":"Doe"}]
  
}
Output should be:
Developer
firstName      lastName
John              Smith
John              Doe

Tester
firstName      lastName
Jane              Doe

Please give me support to display this type of output using mustache ,I try using following syntax
{{#employees}}{{employyee_type}}{{/employees}} but ,It's not working.

**Comment by dasilvacontin** [comment]
Hi @daghera. I'm not sure I get your data structure. For clarity, could you write it in JSON format?
