### ISSUE TITLE
Improve documentation to explain that Inverted Sections uses falsy

### ISSUE THREAD

**Issue by Lukenickerson** [janl/mustache.js#420]
The documentation ([here](https://github.com/janl/mustache.js/#inverted-sections) and [here](http://mustache.github.io/mustache.5.html)) explains:

> The block of an inverted section is rendered only if the value of that section's tag is null, undefined, false, or an empty list.

> they will be rendered if the key doesn't exist, is false, or is an empty list.

But the [spec](https://github.com/mustache/spec/blob/master/specs/inverted.yml) says

> If the data is not of a list type, it is coerced into a list as follows: if the data is truthy (e.g. `!!data == true`), use a single-element list containing the data, otherwise use an empty list.

(From issue #186)

The documentation should be more clear that the inverted section uses *falsy*. Personally I was confused when a value of `0` was triggering the inverted section (I read the docs thinking "*is*" is like `===`).

**Comment by dasilvacontin** [comment]
If no one offers to send a PR, I'll assign this to myself.

**Comment by phillipj** [comment]
Fixed with 5f06df20d20aee2
