### ISSUE TITLE
A semicolon at the first line

### ISSUE THREAD

**Issue by zerob13** [janl/mustache.js#423]
Mustache.js don't have a semicolon at the first line,it may cause some error when concat multiple js-files with Mustache.js

**Comment by dasilvacontin** [comment]
What line? What are you talking about?

**Comment by zerob13** [comment]
I think you need to add a semicolon at the first line . Just like the code blow:

```

/*global define: false*/
;
(function (global, factory) {
  if (typeof exports === "object" && exports) {
    factory(exports); // CommonJS
  } else if (typeof define === "function" && define.amd) {
    define(['exports'], factory); // AMD
  } else {
    factory(global.Mustache = {}); // <script>
  }
}(this, function (mustache) {
...
```

**Comment by zerob13** [comment]
If I don't add this semicolon, it cause some error when I concatenate Mustache and zepto by grunt.

**Comment by zerob13** [comment]
I updated Zepto.js to 1.1.6,this issue has been fixed.

**Comment by bobthecow** [comment]
@zerob13 This indicates a problem with your concatenation method, not a problem with this library :)
