### ISSUE TITLE
Array start from 1

### ISSUE THREAD

**Issue by arminkardovic** [janl/mustache.js#427]
when array start with 1 ex comm: [1]=> object, mustache not work

**Comment by phillipj** [comment]
Hi @arminkardovic,

I'm curious as to why would want to such an array. Could you provide a more in-depth example / scenario and what you would have expected from mustache?

Array with holes are strange beasts... 
- http://speakingjs.com/es5/ch18.html#array_holes
- http://www.2ality.com/2013/07/array-iteration-holes.html

**Comment by arminkardovic** [comment]
If in array first key is 1 it wont interate but if is 0 mustache iterate normaly ... i ask if mustache iterate anyway if start with key 0 or with key 100 for ex.

array(1=> Object, 2=> Object) wont iterate

array(0=> Object, 1=> Object) mustache iterate 

can mustache iterate in bouth way

**Comment by dasilvacontin** [comment]
Hi @arminkardovic, iterating an array that doesn't start with key 0 works for me. Can you submit a sample script that reproduces the issue?

**Comment by dasilvacontin** [comment]
I personally tried with the following one:
```
var Mustache = require('mustache')

var view = {
    arr: [ ,, 'a' ,,, 'b' ,,, 'c']
}

var output = Mustache.render("{{#arr}}{{.}}{{/arr}}", view)

console.log(output)
```
```
[object Object][object Object]a[object Object][object Object]b[object Object][object Object]c
```

**Comment by bobthecow** [comment]
@arminkardovic Are you using mustache.php by any chance?

**Comment by dasilvacontin** [comment]
@bobthecow The way he writes the arrays.. it could be that.

**Comment by arminkardovic** [comment]
Yes i use it in php and array return from function is array(1=>Object, 2=>Object) now i fix that in array(0=>Object, 1=>Object)  and mustache works perfectly but i don't know why mustache wont iterate anyway when i get it with ajax json

**Comment by bobthecow** [comment]
You're asking a question on Mustache.js ;)

https://github.com/bobthecow/mustache.php/wiki/Mustache-Tags#lists-vs-hashes

**Comment by arminkardovic** [comment]
Yes :D

**Comment by arminkardovic** [comment]
Yes but when i get object comm: array (1 => array('name' => 'Some Name') , 2=> array('name' => 'Some Name'))

and tempalte 

{{#comm}} {{#.}} {{name}} {{/.}}{{/comm}} - this give me just one [Object object] but when I redeclare key in array comm: array (0=> array('name' => 'Some Name') , 1=> array('name' => 'Some Name'))

everithing work fine :D

**Comment by bobthecow** [comment]
The link I posted is your answer. Basically, unlike most other languages, in PHP the "array" type is used for both lists and associative arrays. So Mustache.php needs a way to tell whether a given array should be treated as a list, or as a rendering context. The way it tells is it looks for consecutive integer indexes, starting with 0. If the indexes go `0, 1, 2, 3...` it's treated as a list. If the indexes are anything else, it's treated as an associative array (like passing in an object or something).

This repo is for mustache.js. You're having trouble using Mustache.php. They're two different projects, with different developers. That means this is not an appropriate place to continue this conversation :)

**Comment by phillipj** [comment]
Good catch @bobthecow!
