### ISSUE TITLE
Mustache.js template with function fails using command line tool

### ISSUE THREAD

**Issue by hhumml** [janl/mustache.js#429]
Using the examples from the readme section, I get the following exception when trying it with the command line tool (installed with npm):
```
undefined:3
	"bold": function () {
	         ^
SyntaxError: Unexpected token u
    at Object.parse (native)
    at /usr/local/lib/node_modules/mustache/bin/mustache:49:13
    at ReadStream.<anonymous> (/usr/local/lib/node_modules/mustache/bin/mustache:72:5)
    at ReadStream.g (events.js:180:16)
    at ReadStream.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:442:13)
```
View
```
{
	"name": "Tater",
	"bold": function () {
		return function (text, render) {
			return "<b>" + render(text) + "</b>";
		}
	}
}
```
Template
```
{{#bold}}Hi {{name}}.{{/bold}}
```
When trying the same within the browser it works. What am I missing?

Background: I want to build a HTML template generator using the command line tool.

**Comment by dasilvacontin** [comment]
Hi @hhumml, the view argument is supposed to be a .json file. JSON format doesn't support functions.

**Comment by renancarvalhoo** [comment]
@hhumml have example in the documentation of mustache :
<pre>
Template:
<code>
{{#wrapped}}
  {{name}} is awesome.
{{/wrapped}}
</code>
Hash:
<code>
{
  "name": "Willy",
  "wrapped": function() {
    return function(text, render) {
      return "\<b>" + render(text) + "\</b>"
    }
  }
}
</code>
https://mustache.github.io/mustache.5.html

**Comment by dasilvacontin** [comment]
@renancarvalhoo, you can't store functions in .json file.

**Comment by renancarvalhoo** [comment]
i know this but you can work the data in the javascript before pass to template mustache.

**Comment by dasilvacontin** [comment]
@renancarvalhoo, but @hhumml is talking about using the command line tool.

**Comment by watersoona** [comment]
I have the same problem, how to solve it ?
