### ISSUE TITLE
add a more strict linter

### ISSUE THREAD

**Issue by dasilvacontin** [janl/mustache.js#433]
We have strings with both `"` and `'`. I'd like the repo to have a more uniform coding style, tbh.
Thoughts, @phillipj?

**Comment by phillipj** [comment]
Sure, I'm also a `'`-fan :+1: 

[JSCS](http://jscs.info/) has gotten a lot of traction lately. In fact the codestyle rules in JSHint is being deprecated these days in favor of JSCS, so the [quotmark](http://jshint.com/docs/options/#quotmark) option in JSHint will dissapear sometime soon..

**Comment by bobthecow** [comment]
check out eslint. after trying all of 'em, that's where several projects i work on have ended up.

**Comment by phillipj** [comment]
Yeah eslint also does the trick.. Anything other than quotes you had in mind @dasilvacontin?

Although I feel most linters do the basic stuff equally well, some are more suiteable for specific things and custom styles.

**Comment by dasilvacontin** [comment]
Glad you guys mentioned eslint, it's the one I had in mind. :)

More things:

`Writer.prototype._rawValue = function(token) {`
vs
`mustache.parse = function (template, tags) {`

What are your thoughts about `standard`?

**Comment by phillipj** [comment]
My thoughts about the differences:

I like hinting about how "public" my functions are. Therefore I often tend to add an `_` for "private" and usually very specific functions, e.g.  `function _somewhatPrivate(){}`

I dont have a strong preference about spaces in function declarations. Looking at the source atm, there's mostly spaces `function () {}`, which means I have to fix my wrongly formatted Writer functions :smiley:

My two main reason for choosing the `prototype`-style today: better stack traces and memory profiling. Prototypes also helps raw performance, but that is usually not a big concern before running hot code which executes **alot**.

**Comment by dasilvacontin** [comment]
> I dont have a strong preference about spaces in function declarations.

I don't have a preference about either style, but I like them to look the same. Will merge PR for those changes. :)

**Comment by dasilvacontin** [comment]
> I like hinting about how "public" my functions are. Therefore I often tend to add an _ for "private" and usually very specific functions, e.g. function _somewhatPrivate(){}

I usually just note it in the function's documentation and that's all.

Also, I like to name anonymous functions. Better stacktraces, as you mentioned, and more contribution-friendly code. :)

**Comment by phillipj** [comment]
Btw, #412 has fixed alot of mixed styles.. Personally havent had any experience with google closure compiler though, ref my question about the benefits compared to jshint (or eslint for that matter)

**Comment by dasilvacontin** [comment]
I agree, and I would merge it if it didn't have conflicts.We could try adding eslint after I merge my v2.0 PR.
