### ISSUE TITLE
TypeError in firefox if there is a tag named "watch".

### ISSUE THREAD

**Issue by Lukesed** [janl/mustache.js#442]
Minimal example:
Mustache.render("{{watch}}", {watch: "test"})

Result in Chrome 41:
"test"

Result in Firefox 37:
TypeError: missing argument 1 when calling function value.call

Perhaps it's caused by this: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/watch

**Comment by dasilvacontin** [comment]
Thanks for reporting! :)

**Comment by phillipj** [comment]
I havent been able to reproduce this in firefox @Lukesed. Tried both locally with scripts and firebug + [browserstack](https://www.browserstack.com/).

How did you run your example too trigger that error? What exact firefox version and OS are you on?

**Comment by Lukesed** [comment]
Error appears in the console when running this: https://jsfiddle.net/uno2xw56/

Firefox version 37.0.2, OS X 10.10.3.

**Comment by Eschon** [comment]
Also appears on Firefox 39.0a2, OS X 10.10.3

**Comment by phillipj** [comment]
Thanks guys! Confirmed the error after realizing I had a bug in my browser tests script. 

Bugfix coming soon :)
