### ISSUE TITLE
Can i perform if-else command on this?

### ISSUE THREAD

**Issue by soledadtctvtn** [janl/mustache.js#444]
Is it more compatible on this engine? How can i do this?

**Comment by bobthecow** [comment]
You can, like this:

```html+jinja
{{# cake }}there will be cake!{{/ cake }}{{^ cake }}the cake is a lie.{{/ cake }}
```

**Comment by soledadtctvtn** [comment]
It's cool, thanks @bobthecow  ;)

**Comment by soledadtctvtn** [comment]
Hi @bobthecow ,

How can i perform expression look like this:

{{# items.length < 2 }} At least three items or more plzz{{/ items }}
{{^ items }} Name: {{.}} {{/ items }}

**Comment by bobthecow** [comment]
You can't use expressions inside your template, because that's logic. And mustache is a logic-less templating language. 

The proper way to do this is to prepare the data before passing it to the render function.

**Comment by soledadtctvtn** [comment]
Yeap, tks @bobthecow

**Comment by dasilvacontin** [comment]
@bobthecow is the man :shipit:

**Comment by bobthecow** [comment]
No problem.
