### ISSUE TITLE
jQuery wrapper incomplete ?

### ISSUE THREAD

**Issue by Kitof** [janl/mustache.js#447]
Since  2 years, my website use https://github.com/jonnyreeves/jquery-Mustache and an outdated version of mustache.js.

I try to upgrade in order to remove jquery-Mustache plugin since mustache.js supports specific jquery wrapper.

But, i used to preload a lot of small templates with $.Mustache.load and jquery-Mustache. It seems that i'm only able to use Mustache.render with the new wrapper.

**Comment by phillipj** [comment]
Hi @Kitof,

As all our wrappers, the jQuery wrapper focuses on wrapping `Mustache.render()` in that specific framework. jquery-Mustache seems to have a much broader scope, packing alot more jquery utilities aswell. With that said I dont think of our jQuery wrapper as incomplete.

jquery-Mustache seems compatible with v2.0.0 of mustache.js in my initial tests. If you heavily depend on  `$.Mustache.load()` you could probably still use it?

**Comment by Kitof** [comment]
Thanks for your answer.

Actually, i'm not able to use jquery-Mustache with requireJS. So maybe i'll try to open an issue there, but it seems not to be maintained anymore (no more commit since 2 years).

**Comment by phillipj** [comment]
Ahhh, I see.. Guess that would be a good addition to jquery-Mustache, hopefully you'll get some response from the author.

Closing this for now as it doesnt seem like a mustache.js issue.
