### ISSUE TITLE
Auto focusing upon render

### ISSUE THREAD

**Issue by dvbondoy** [janl/mustache.js#452]
Hi, I'm trying to use Mustache on an android app, I'm using webview. I've noticed that when I'm rendering an element it's seems that mustache randomly focusing/activating (example:a button is clicked on render) a rendered element after. I'm sorry if this is a duplicate post but I already perused closed issues but found none like my issue.

**Comment by phillipj** [comment]
Hi @dvbondoy!

Code examples would greatly help us debug this issue.

mustache itself doesnt focus or activate buttons. In your example I assume mustache is generating HTML to be displayed in the webview. In HTML one can add attributes on inputs signaling it should get focus, is that what you are doing? Or maybe you have some clientside javascripts running?

**Comment by dvbondoy** [comment]
Hello @phillipj sorry i forgot to give more details. you're right i use mustache to generate part of my html file to pass object on my static html. i don't want to focus or trigger and element or inputs upon loading. what's bugging me for days is that when my static page load, that part that mustache rendered are being triggered like a link or a button. i'm not really sure if it's mustache fault or webview itself. Here's some of my code..

//note:placed at the bottom of my static page
<script type="x-tmpl-mustache" id="accounts_tmpl">
    {{ #accounts }}
    <a class="list-group-item" href="#" id="{{_id}}">
        <img src="img/pic.jpg" class="img-rounded pull-left">
        <h4 class="list-group-item-heading">{{ name }}</h4>
        <p class="list-group-item-text">{{ store }}</p>
    </a>
    {{ /accounts }}
</script>

//note:placed at the bottom my static page
$("#account_list").html(function(){
        var template = $("#accounts_tmpl").html();
        var render = Mustache.render(template, {"accounts":JSON.parse(accounts)});
        $(this).html(render);
    });

//note:place in a separate js file
 bootcards.init( {
    offCanvasBackdrop : true,
    offCanvasHideOnMainClick : true,
    enableTabletPortraitMode : true,
    disableRubberBanding : true,
    disableBreakoutSelector : 'a.no-break-out'
    });

//and the part rendered by mustache
<div id="account_list" class="list-group">
            
</div>

**Comment by dasilvacontin** [comment]
Could you use markdown to style that code? It's a bit hard to guess what you are trying to show.

https://help.github.com/articles/github-flavored-markdown/

**Comment by dvbondoy** [comment]
Hi @dasilvacontin sorry i wasn't aware of that that Markdown, my first time to comment a code. Anyway i just found the culprit. i did try to disable fastclick.js and my problem is gone. i would really appreciate if some of you can give an advice where i can still use fastclick.js along with mustache. Thanks a lot.

**Comment by dvbondoy** [comment]
Just read fastclickjs docs and i think i found a way. Thanks a lot @dasilvacontin and @phillipj . You guys are awesome. This is my first time to use mustache and it's awesome.

**Comment by dasilvacontin** [comment]
No worries! Feel free to ask again when in doubt. :)
