### ISSUE TITLE
make 'hooks/install-hooks.sh' more verbose

### ISSUE THREAD

**Issue by dasilvacontin** [janl/mustache.js#462]
You currently can't tell much of what happened.

**Comment by ShashankaNataraj** [comment]
@dasilvacontin Can I take this up?

**Comment by dasilvacontin** [comment]
Sure, no problemo, thanks!

**Comment by ShashankaNataraj** [comment]
@dasilvacontin Does this issue need to be closed?

**Comment by dasilvacontin** [comment]
Indeed!
