### ISSUE TITLE
Add error handling when view is not an object in render()

### ISSUE THREAD

**Issue by morena** [janl/mustache.js#464]
I got stuck with this error for a long while "Uncaught TypeError: this.tail.search is not a function" and in the end somebody helped by pointing out I was passing render() an array rather than object for view.
I know a lot of people won't have issues with this, but as I explained in my post  http://morenafiore.com/2-things-i-did-not-understand-about-mustache/ it might help people who approach Mustache.js for the first time to not give up by having more specific errors displaying.

Other people had this error, but it was down to template not being passed as plain text  http://stackoverflow.com/questions/10872615/what-is-the-difference-between-mustache-render-and-mustache-to-html

I hope you might be able to help :)

**Comment by phillipj** [comment]
Hi @morena,

IMO we should absolutely write APIs which helps you as a developer, rather than you having to delve into the source code. I'm all for throwing a `TypeError` with an informative error message if we get anything else than an object provided for `mustache.render()`.

Thanks for writing a tutorial on using mustache.js! :+1:

**Comment by dasilvacontin** [comment]
Great post @morena, thanks for the thoughts!

I agree with @phillipj; the library should be more dev friendly, especially for newcomers.

**Comment by morena** [comment]
Thanks! I would like to help but I think I might not have the right skills yet

**Comment by dasilvacontin** [comment]
No worries, reporting this issue was great already! :)

**Comment by phillipj** [comment]
I've been looking at this issue now and just realized I was probably too quick when answering the first time. An `array` as a view should not be a problem. Although I reproduced the error you mentioned when providing `Mustache.render()` with anything else than a `string` as the template. Could that be your case too?

```js
Mustache.render('{{#.}}{{.}} {{/.}}', ['hello', 'world']);
// -> hello world
```

Though wrapping the first argument into e.g. an array throws the tail.search error.

**Comment by SoEpe** [comment]
Today it is working for me, after daily reboot perhaps?
Should have done reboot at first glance.
