### ISSUE TITLE
Quick question

### ISSUE THREAD

**Issue by dvbondoy** [janl/mustache.js#465]
Hello. how can i achieve this template in mustache?
```javascript
{{#category}}
  {{#item}}
     {{item_name}}
  {{/item}}
{{/category}}
```
what is the best way to structure my data? i have a raw data, i know how to manipulate and rearrange it if needed. thanks in advance

**Comment by bobthecow** [comment]
Are you trying to loop over categories, and loop over items in each category? Something like this should do the trick:

```js
{
  category: [
    {
      item: [
        {item_name: 'Foo', /* ... */},
        {item_name: 'Bar', /* ... */},
        // ...
      ]
    },
    {
      // ...
    }
  ]
}
```

**Comment by dvbondoy** [comment]
yes @bobthecow . i'll try this one. in your example however i can't see where to put my categories.

thanks a lot..been thinking about how to achieve this since yesterday.

**Comment by dvbondoy** [comment]
@bobthecow solve my problem..thanks a lot..i just re-structure your sample code...i end up like this

```javascript
var CATEGORIES = {
            categories:[
                {category:"category1",
                items:[{item:"item1"},{item:"item2"}]},
                {category:"category2",
                items:[{item:"item3"},{item:"item3"}]}
            ]
        };
```

thanks a lot for your help..God bless you

**Comment by bobthecow** [comment]
No problem!
