### ISSUE TITLE
Image loading browser request from template

### ISSUE THREAD

**Issue by kosmom** [janl/mustache.js#470]
When used template
```html
<div id="template">
<img src="{{PIC}}.png">
</div>
```
Browser try get image with {{PIC}}.png url
how can avoid additional request?

**Comment by Romanx** [comment]
If your template is in a normal HTML block then it'll attempt to load what it thinks is an image. I'd recommend putting your template in a script where it won't attempt to load the image and then in javascript load your template from there.

**Comment by phillipj** [comment]
Try using a script element instead of div.

```html
<script type="text/mustache" id="template">
    <img src="{{PIC}}.png">
</script>
```

**Comment by kosmom** [comment]
Thats working, thank you
Text editor highlight broken, but it's another problem

**Comment by dasilvacontin** [comment]
I understand this is closed. Let us know otherwise. :)
