### ISSUE TITLE
Question not an issue: Render array instead of string

### ISSUE THREAD

**Issue by Wikunia** [janl/mustache.js#475]
Hey guys,

I want to render only a part of the html and I would like to use the rendered array structure for it.
This one is the generated structure:

```
[
  [
    "text",
    "<ul>\r\n",
    0,
    6
  ],
  [
    "#",
    "test",
    6,
    17,
    [
      [
        "text",
        "    <li>Nr:  ",
        19,
        32
      ],
      [
        "name",
        "nr",
        32,
        38
      ],
      [
        "text",
        "</li>\r\n",
        38,
        45
      ]
    ],
    45
  ],
  [
    "text",
    "</ul>",
    58,
    63
  ]
]

```

I would like to render only a part of it:
```
[
  "#",
  "test",
  6,
  17,
  [
    [
      "text",
      "    <li>Nr:  ",
      19,
      32
    ],
    [
      "name",
      "nr",
      32,
      38
    ],
    [
      "text",
      "</li>\r\n",
      38,
      45
    ]
  ],
  45
]
```

Is there any way to do it directly or do I need to regenerate the html out of it? 
Thanks in advance!

**Comment by ShashankaNataraj** [comment]
Ask questions on stackoverflow, not on github issues.

**Comment by dasilvacontin** [comment]
It wouldn't hurt to be a bit more polite/happy though.

**Comment by ShashankaNataraj** [comment]
@dasilvacontin @Wikunia Sorry lack of sleep must be getting to me. Now that I read my comment again I realize I came off as grumpy. Apologies!

**Comment by dasilvacontin** [comment]
Thanks! That's much better, and constructive also. :)
