### ISSUE TITLE
Percent Sign (%) in HTML

### ISSUE THREAD

**Issue by krlbaker** [janl/mustache.js#477]
I have a mustache template that I am using the three curly braces to render the data as HTML. In the HTML there is a percent sign. When the page renders the percent sign breaks the page. If I take out the percent, everything is good. Suggestions? Known issues?

```javascript
var description = '<p>I am 100% positive, you should answer yes to the question.</p>';
<div>{{{description}}}</div >
```

**Comment by Romanx** [comment]
That should work exactly as you intend and i just confirmed that using [www.trymustache.com](trymustache.com). Are you sure nothing else could be causing the issue. Could you provide a code sample?

**Comment by krlbaker** [comment]
I don't know what happened, now it is working. I deleted the text and re-added it to the database. I am assuming someone pasted from Word, which we all know is bad... Thanks Romanx for the reply.

**Comment by Romanx** [comment]
You're welcome. You need to close the issue to mark it as resolved :smile:

**Comment by dasilvacontin** [comment]
Closing the issue. I'm glad you got it working. :)
