### ISSUE TITLE
Implement the "fs" module to parse / render files directly.

### ISSUE THREAD

**Issue by JamenMarz** [janl/mustache.js#478]
As far as NodeJS goes, I'd like to see "fs" get implemented so we can parse files directly...  Here is an example for rendering:

```javascript
var mst = require("mustache");

var rendered = mst.renderFile(__dirname + "someTemplate.mustache", {
  "someData": "foobar"
});
```

As of right now, we currently have to do:

```javascript
var mst = require("mustache"),
    fs = require("fs");

var rendered = mst.render(fs.readFileSync(__dirname + "someTemplate.mustache").toString(), {
  "someData": "foobar"
});
```

Or the async counterpart (which I left out, because it would feel out of style to Mustache's synchronous style).

**Comment by phillipj** [comment]
Sounds like a good idea for a separate npm module for node exlusively :+1: 

mustache.js is just as much a browser module as a node module. There is no filesystem in the browser.

**Comment by dasilvacontin** [comment]
There's a nice transform for browserify, btw: https://www.npmjs.com/package/brfs.

**Comment by JamenMarz** [comment]
Alright, I understand, perhaps I'll fork this and add in some NodeJS related features.

**Comment by bobthecow** [comment]
@JamenMarz You don't need to fork it, you can write a node-specific package that implements the more node features but under the hood uses this library.

**Comment by phillipj** [comment]
I could help you out with getting that module created and published if you
want @JamenMarz, just say the word!

**Comment by JamenMarz** [comment]
@bobthecow You have a good point, but there is things I'd prefer to implement into the library itself if I were to fork it, such as buffers.

Like you all have said, Mustache.js aims to be just as compliant with the browser as it is to NodeJS.  So even if we were to add a polyfill for something like buffers, it would seem messy on browsers because then the whole library would be working through polyfills, simply yucky.  

So in some situations, like this one, perhaps it's best to fork it and redesign it a little instead of building onto it with another module?
