### ISSUE TITLE
allowing the use of partials from CLI

### ISSUE THREAD

**Issue by mattecapu** [janl/mustache.js#483]
I noticed that running
```
mustache data.json template.mustache
```
Where `template.mustache` uses some partial template, they are not resolved.

I propose to add a new argument (something like `--partial/-p`), that you can use multiple times, to populate the `partials` object when compiling the template.
For example:
```
mustache data.json -p partial1.mustache -p partial2.mustache template.mustache
```
Or any other variation of the syntax, if someone dislikes it.

Otherwise it would seem natural to me to automatically fetch `<partial>.mustache` whenever `{{> <partial>}}` is used in a template, but I understand this could be a huge change.

**Comment by phillipj** [comment]
I like your idea about adding a new argument to specify partials :+1:
