### ISSUE TITLE
Install instructions are way to down into the README

### ISSUE THREAD

**Issue by mateusortiz** [janl/mustache.js#493]
Creating a package on bower or npm, be more easy to get mustache.

**Comment by phillipj** [comment]
We are already?

http://bower.io/search/?q=Mustache and
https://www.npmjs.com/package/mustache

**Comment by dasilvacontin** [comment]
Most users expect the `install` part of the readme near the top. That should be improved – currently you have to scroll a lot.

**Comment by mateusortiz** [comment]
Sorry I didn't notice, I can improve it, ok @dasilvacontin?

**Comment by dasilvacontin** [comment]
Nice, a PR is welcome, @mateusortiz! Though if you can't do it today, don't worry then. Either @phillipj or myself will take care of it asap due to Hacktoberfest – it's an important piece of information to highlight at the top.

**Comment by dasilvacontin** [comment]
Nice, a PR is welcome, @mateusortiz! Though if you can't do it today, don't worry then. Either @phillipj or myself will take care of it asap due to Hacktoberfest – it's an important piece of information to highlight at the top.

**Comment by mateusortiz** [comment]
I'm also participating on the hacktoberfest

**Comment by dasilvacontin** [comment]
Closed via https://github.com/janl/mustache.js/pull/496.
