### ISSUE TITLE
Mustache escapes '\'  in {{{.}}}

### ISSUE THREAD

**Issue by kirtangajjar** [janl/mustache.js#507]
According to the documentation, `{{{}}}` will render pure html, not escaped, however i just observed it does escapes `\` character.

To see it in action, try `Mustache.render('<div>{{{.}}}</div>','<input id="email" pattern="^.{5,20}@\w{3,8}\..{2,5}$">');`

its output will be `<div><input id="email" pattern="^.{5,20}@w{3,8}..{2,5}$"></div>`.
Instead it should be `<div><input id="email" pattern="^.{5,20}@\w{3,8}\..{2,5}$"></div>`

**Comment by phillipj** [comment]
Its due to not escaping the string literal properly. You'll need to add a couple of backslashes for it to work as you intended:
```js
Mustache.render('<div>{{{.}}}</div>','<input id="email" pattern="^.{5,20}@\\w{3,8}\\..{2,5}$">')
```
