### ISSUE TITLE
How to pass Mustache in link in ASP.NET??

### ISSUE THREAD

**Issue by AdvantmedKinjal** [janl/mustache.js#520]
Hello All,

I am using ASP.NET 4.5 Web application using Mustache js.
In one of my requirement I am pass mustache value by query string like

`<a href="RecordFlow_Request.aspx?requester={{ClientName}}">{{OrderCount}}</a>`
**here output is** : requester=abc 
It is actual result which I want.

It's working fine but when I try to pass by following way::
`<a href='Record.aspx??<%=WebUtility.GetEncryptedQueryString("requester={{ClientName}}")%>'>{{OrderCount}}</a>`

When I decrypt It's getting like "**requester={{ClientName}}**" instead of "**requester=abc**".
Here 'abc' is ClientName.

Can Any one help me immediately?

Thanks in Advance

**Comment by phillipj** [comment]
It would be helpful with more info about your current setup, e.g. what mustache libraries are you using? 

Assuming your first successful example is pure client side HTML and JavaScript with mustache.js, the second example is something quite different. When you utilize `<%=WebUtility.GetEncryptedQueryString("requester={{ClientName}}")%>` you're suddenly in the world of ASP.NET, not JavaScript.

Are you using [Nustache](https://github.com/jdiamond/Nustache) or [ASP](https://github.com/nagaozen/asp-xtreme-evolution/blob/master/lib/axe/classes/Parsers/mustache.asp) to support mustache when in C#/ASP?

**Comment by Romanx** [comment]
As the current maintainer of Nustache it doesn't seem to be using that. I would guess in this case `WebUtility.GetEncryptedQueryString` is returning `requester={{ClientName}}` and it's not being interpolated by anything.

As @phillipj requested more information about what you're using to template would help

**Comment by phillipj** [comment]
Thanks @Romanx!

**Comment by AdvantmedKinjal** [comment]
Hi,
I am using "ASP".And mustache 0.8.1 download from GitHub. And I want to pass Query string parameter in encrypted form,so I use second case
