### ISSUE TITLE
Create alias "shave" for method "render"

### ISSUE THREAD

**Issue by kib357** [janl/mustache.js#522]
I think it will make use of the library more intuitive)

**Comment by phillipj** [comment]
Dont you have to `groom()` before shaving aswell?

**Comment by kib357** [comment]
My mustaches is usually short, but fans of long mustaches should enjoy grooming.

**Comment by sveisvei** [comment]
My mustaches  would also like `trim()` to always be called on the result by default.

**Comment by phillipj** [comment]
So... In all honesty, I dont see `shave()` landing in mustache.js core as it's not part of the (boring?) [mustache spec](https://mustache.github.io/). Create your own npm module which uses mustache.js under the hood, for a more natural and intuitive API? :smile_cat:

**Comment by dasilvacontin** [comment]
We save this thread for April fools tho.
