### ISSUE TITLE
render select ?

### ISSUE THREAD

**Issue by mqliutie** [janl/mustache.js#537]
data structure like below:
```js
var res = {
    results: [{
        name: '1'
    }, {
        name: '2'
    }]
};
var template = $('select').html();
Musache.render(tempalte,res);
```
html template :
```XML
<select>
{{#results}}
    <option>{{name}}</option>
{{/results}}
</select>
``` 
But result as below pic
![](http://pic.i-yizhan.com/uploads/567908eb433f9.jpeg)

**Comment by mqliutie** [comment]
there is a '{{}}'

**Comment by Romanx** [comment]
Your syntax looks correct and it works when I test it in [http://trymustache.com/](http://trymustache.com/). Your example has a typo `Musache.render(tempalte,res);` here but i'm more inclined to think that `$('select').html();` is causing your template to change from what you expect.

Could you try put your template in-line and see if that works?

**Comment by mqliutie** [comment]
sorry,I knew why this problem happened
