### ISSUE TITLE
string '0' treated not treated as falsey

### ISSUE THREAD

**Issue by BenKelada** [janl/mustache.js#539]
javascript treats a string '0' as falsey, but it doesnt appear that mustache js treats a string 0 a falsey

mydata = '0'
{{mydata}} {{^mydata}} Parentmydatafalsey{{/mydata}} {{#mydata}} mydata truthy{{/mydata}}

**Comment by bobthecow** [comment]
JavaScript doesn't treat string '0' as falsey:

<img width="762" alt="screen shot 2016-01-06 at 10 38 37 pm" src="https://cloud.githubusercontent.com/assets/53660/12163927/42c983e0-b4c6-11e5-8922-078c2ed4a640.png">

**Comment by BenKelada** [comment]
thanks might be a moodle implementation  thing I'll look harder...

**Comment by BenKelada** [comment]
oh oops misread...  i only tried 
'0' == false 
thanks

**Comment by eshansingh** [comment]
@BenKelada You should probably close this issue then.
