### ISSUE TITLE
Add support for specifying partial tags

### ISSUE THREAD

**Issue by msmith-techempower** [janl/mustache.js#541]
Similar to how one can set the delimiter tags, it would be helpful to be able to do the same with partials.

The impetus for this is that I have been playing around with HTMLImports for specifying and loading template/partial html files, but when trying to load them in JavaScript, the `{{> foo}}` gets automatically mangled to `{{&gt; foo}}`, which then causes MustacheJS to fail on compilation of the template.

Being able to configure MustacheJS to use something like `{{~ foo}}` (or something else that would not be html entity encoded automatically) would be kind of useful.

**Comment by phillipj** [comment]
Thanks for reporting!

I'm usually not in favor of adding features in mustache.js which doesn't exist in the [mustache spec](https://mustache.github.io/mustache.5.html), but this might be actually be an exception. This is probably unique to JavaScript as it lives in the browser and gets affected by HTMLImports. Meaning mustache implementations in other languages wouldn't have the need to implement this.

I haven't played much with HTMLImports yet... Have you found any other issues using mustache.js with imports @msmith-techempower?

/cc @dasilvacontin

**Comment by msmith-techempower** [comment]
Thanks for the reply! I love the project!

Really, the only issue I have seen so far, and I have admittedly only been playing with HTMLImports for the last few days so take this with a grain of salt, is that the browsers parse and execute each document as html and only allow that built document to be accessed via JavaScript.

It feels like for MustacheJS specifically (like you said, it doesn't make much sense to implement for Java etc) requires markup that will not be automatically entity encoded by the browser. Now, I am a pretty trivial-level user of Mustache, so I can only speak for the items in the readme (templates, blocks, conditionals, partials, etc), but I believe that the partial markup is the only place where html entity encoding becomes a problem (`{{> foo}}` -> `{{&gt; foo}}`), but it would be good for an expert on Mustache to confirm this.

**Comment by bobthecow** [comment]
Can you paste some code? I'm trying it and not running into any trouble at all.

**Comment by msmith-techempower** [comment]
Sure thing; here's a really simple example I have been playing around with:

**template.html**
```html
<template>
  {{> partial}}
</template>
```

**partial.html**
```html
<template>
  <div>{{message}}</div>
</template>
```

**index.html**
```html
<!DOCTYPE html>
<html>
  <head>
    <title>Test</title>
    <script type="text/javascript" src="/js/webcomponents.min.js"></script>
    <script type="text/javascript" src="/js/mustache.js"></script>
    
    <link rel="import" id="template" href="/templates/template.html" />
    <link rel="import" id="partial" href="/templates/partial.html" />
    
    <script type="text/javascript">
      window.addEventListener('HTMLImportsLoaded', function(e) {
        var template = document.querySelector('#template').import.querySelector('template').innerHTML,
            partial = document.querySelector('#partial').import.querySelector('template').innerHTML,
            context = {message: "This is a test"},
            html = Mustache.render(template, context, { partial: partial });

        console.log(template); // "{{&gt; partial}}"
        console.log(partial);  // "<div>{{message}}</div>"
        console.log(html);     // ""

        document.body.innerHTML = html;
      });
     </script>
  </head>
  <body>
    <div>Testing styles</div>
  </body>
</html>
```

For reference, if I change the html line to `html = Mustache.render(partial, context);` then everything works as expected; it's that `&gt;` that seems to be gumming up the works.

**Comment by bobthecow** [comment]
Gotcha. Your problem has nothing to do with HTMLImports and everything to do with the fact that mustache is fundamentally incapable of being treated as HTML :)

For example, this is valid mustache:

```html+jinja
<input {{#isDisabled}}disabled{{/isDisabled}}/>
```

… but it'll blow up if you put it in a `<template>` or `<div>`, with or without HTMLImports.

You should be using script tags and `innerText` instead of `innerHTML` for mustache templates in your imported html file, just like you should be using script tags if you inline mustache templates into your main file. The first of these will work, the second will esplode:

```html+jinja
<script type="text/mustache" id="foo">
  {{> partial }}
  <input {{#isDisabled}}disabled{{/isDisabled}}>
</script>

<template id="bar">
  {{> partial }}
  <input {{#isDisabled}}disabled{{/isDisabled}}>
</template>
```

**Comment by msmith-techempower** [comment]
@bobthecow Thanks for the help on this one; seems you have riddled it out. Though, I admit that I am frustrated at having to use script tags to bend the browser to my will.

I suppose that what I really wanted was the ability to treat HTMLImports as a "fetch this file and let me have the contents" rather than what it really is: "fetch this html document, parse, and execute it".

Being forced to use script tags to encapsulate my templates/partials is unsavory for a number of reasons, but at least this has resolved my issue specifically.

Thanks for the support and keep up the great work!

**Comment by bobthecow** [comment]
Yep. It's unfortunate, though understandable, that `<template>` elements are just a special case of document fragment. And using `<script>` is definitely ugly. But it's currently the only way (in HTML) to have an invalid or somewhat partially valid HTML string without everything going sideways.

**Comment by msmith-techempower** [comment]
Agreed, I see the problem clearly now.

At least I can continue playing around with HTMLImports knowing that MustacheJS is working appropriately :-).

**Comment by phillipj** [comment]
What should we have done without @bobthecow... Thanks for pitching in! :+1:

**Comment by dasilvacontin** [comment]
Same, thanks @bobthecow. :)

**Comment by bobthecow** [comment]
No problem.

**Comment by adjenks** [comment]
You might also be able to stuff them in a data-x attribute. It would be ugly though...

`<div id="template" data-template="<span>{{gross}}</span>"></div>`
