### ISSUE TITLE
Is it possible to manage or handle missing/undefined keys?

### ISSUE THREAD

**Issue by da99** [janl/mustache.js#550]
If the key in the view is missing/non-existent, is it possible to handle this by throwing an error or calling a callback?

Or would such a behavior go against the Mustache spec?

**Comment by RomLAURENT** [comment]
Hi,
specs explicitly define that missing context should be resolved as empty string :
- lines 104 to 123 in https://github.com/mustache/spec/blob/master/specs/interpolation.yml
- lines 135 to 139 in https://github.com/mustache/spec/blob/master/specs/sections.yml 

Maybe could you use helpers to do that?

**Comment by da99** [comment]
You're right. Thanks for the suggestion. I'll close the issue.
