### ISSUE TITLE
Partial do not inherit indentation.

### ISSUE THREAD

**Issue by kuldeepdhaka** [janl/mustache.js#562]
```
var mustache = require("mustache")
var tmpl = "\t{{> test}}"
var data = {}
var partials = {"test": "Tested\nMulti line"}
console.log(mustache.render(tmpl, data, partials))
```

(NodeJS)

this printed

```
    Tested
Multi line
```

but i was expecting.

```
    Tested
    Multi line
```

**Comment by kuldeepdhaka** [comment]
Beautiful code have proper indentation.

**Comment by kuldeepdhaka** [comment]
https://github.com/mustache/spec/blob/master/specs/partials.yml#L13-L15

**Comment by dasilvacontin** [comment]
Interesting, I didn't know about that part of the spec. We probably don't have any tests for that. Thanks for pointing it out!

**Comment by brettstack** [comment]
Any update?

**Comment by idefixcert** [comment]
could you fix this?
or ist there a workaround for that ?

**Comment by balazser** [comment]
Could other mustache implementations solve it? 
This feature is necessary for generating indentation based blocks.

**Comment by yotammadem** [comment]
I've added a proposed solution which fully complies with the partials spec.
The solution includes tests to all the scenarios described in the spec.
If anyone can review and merge this issue can be closed

**Comment by yotammadem** [comment]
As indicated in the PR, I decided to take @kevindew 's solution and merged it with the partial spec tests I've added.  
Now it looks much better. 
Please review

**Comment by phillipj** [comment]
This got fixed in https://github.com/janl/mustache.js/pull/705.
