### ISSUE TITLE
Inverted sections are giving precedence to parent properties rather than its own

### ISSUE THREAD

**Issue by mourasman** [janl/mustache.js#568]
Here's an example: http://jsfiddle.net/mourasman/2gdrvspu/

I came across this problem when I was trying to render a JSON object with nested arrays and I was using a property to know when I had to write or not the comma. It was exactly this solution I was trying to implement: http://stackoverflow.com/a/7591866

Basically, mustache is getting confused with the ambiguity when you have nested sections and you're using the same property name in all of them. Given that the parent and child have a property with the same name, he's reading the parent's property first instead of its own.

**Comment by bobthecow** [comment]
The problem in your fiddle is that the child _doesn't_ have the `last` property, so it looks up the value from the parent. This isn't ambiguity, it's now Mustache is designed to work. Change your data to this and it works as expected:

```
var data = {
  author: "Jones",
  slides: [
    { title: "Hat", colors: [{name: "black"}, {name: "pink", last: true}] },
    { title: "Cat", colors: [{name: "red", last: false}, {name: "green", last: true}], last: true }
  ]
}
```

**Comment by mourasman** [comment]
Yes, that makes sense! Thank you for the clarification and sorry for the false alarm! :)

Closing the issue...
