### ISSUE TITLE
Probleme with nested table

### ISSUE THREAD

**Issue by stefdelec** [janl/mustache.js#571]
Hi,

I am using bootstrap and moustache Js.

`<div id="prestationlist">
    {{#oneprestation}}
    <div class="panel panel-default">

        <div class="panel-heading">
            <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion-example" href="#collapseOne">
                {{date}}{{status}}
            </a>
        </div>
        <div id="collapseOne" class="panel-collapse collapse" style="height: auto;">
            <div class="panel-body">
                <table class=" table table-hover">

                    <thead>
                        <tr>
                            <th>Prestation</th>
                            <th>Status</th>
                            <th>Où</th>
                            <th>Date</th>
                            <th>Points</th>
                        </tr>
                    </thead>

                    <tbody>
                        {{#tableitem}}
                        <tr>
                            <td></td>
                            <td>{{item1}}</td>
                            <td>{{item2}}</td>
                        </tr>
                        {{/tableitem}}
                    </tbody>

                </table>

            </div> 
        </div>

        
        

    </div>
    {{/oneprestation}}
</div>`

Here is my code. First part is displayed perfectly. tableitem is not injected. If i am moustaching it outside from the table it is working. And if I am looking at the HTML the are not injected.

**Comment by amoludage** [comment]
@stefdelec how you are passing the data to this template?? 
Can you please add JavaScript code ??

**Comment by stefdelec** [comment]
Sorry here it is:
    var Dataprestations = {
        oneprestation: [
        {
            "status":"en cours",
            "date":"du 18/05/2016 au 30/05/2016",
            "laprestation":"aide ménagère : 12h de repassage",
            "heureafaire": "12h",
            "coutpoints": "500 points",
            "prisencharge": "pris en charge",
            "declaration": "Hospitalisation",
            "n": 1,
            "tableitem":[
            {
                "item1": "7h",
                "item2": "Azae",            
           },
             {
                "item1": "78h",
                "item2": "zzzzz",            
           },
            ],

        },
        ]
    };

 var templateprestation = $("#prestationlist").html();
    $("#prestationlist").remove();
    var htmlprestation = Mustache.to_html(templateprestation, Dataprestations);
    $("#accordion-example").append(htmlprestation);

**Comment by amoludage** [comment]
where is your `#accordion-example` id that you are appending contents. 

Could you please add whole html content, So that I can help you?

**Comment by stefdelec** [comment]
Ok. Sorry. I thought it would be enough. Here it is thanks for your help.
Also the   {{date}}{{status}} are displayed perfectly. It is not working only inside the table. If i put the loop "tableitem" outside the table it is working.


 <div class="panel-group" id="accordion-example">
                                                <div id="prestationlist">
{{#oneprestation}}
    <div class="panel-heading">
        <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion-example" href="#collapseOne">
            {{date}}{{status}}
        </a>
    </div>
    <div id="collapseOne" class="panel-collapse collapse" style="height: auto;">
        <div class="panel-body">
            <table class=" table table-hover">

                <thead>
                    <tr>
                        <th>Prestation</th>
                        <th>Status</th>
                        <th>Où</th>
                        <th>Date</th>
                        <th>Points</th>
                    </tr>
                </thead>

                <tbody>
                    {{#tableitem}}
                    <tr>
                        <td></td>
                        <td>{{item1}}</td>
                        <td>{{item2}}</td>
                    </tr>
                    {{/tableitem}}
                </tbody>

            </table>


        </div> 
    </div>

    
    

</div>
{{/oneprestation}}

</div>
</div>

**Comment by amoludage** [comment]
Please try replacing `<div id="prestationlist">`  with  `<script id="prestationlist" type="text-template">` this might be help you.

**Comment by stefdelec** [comment]
Yep. Working fine now. Thanks for your help ! It is saving me a lot of time!

**Comment by amoludage** [comment]
:smile:  Great
