### ISSUE TITLE
String.length in lookup

### ISSUE THREAD

**Issue by Eliak** [janl/mustache.js#589]
`Mustache.render('{{#list}}{{a.length}}{{/list}}', {list: [{a: 'a'}]}) === ""`
When: `Mustache.render('{{a.length}}', {a: 'a'}) === "1"`

**Comment by dasilvacontin** [comment]
Afaik `{{a.length}}` should render as `''` in both cases.

**Comment by raymond-lam** [comment]
I believe this is actually a particular manifestation of a more general bug. See PR #618
