### ISSUE TITLE
Error catching blocking usage

### ISSUE THREAD

**Issue by tvld** [janl/mustache.js#606]
Our users write their own, simple few lines, templates. And of course make some typos. The errors that Mustache throw are nasty. They  should be nice for end users, so they can test their template and improve if there are mistakes...

Minimum is normal callback with error so we can catch it...

Or am I missing something?

**Comment by phillipj** [comment]
Rendering is a synchronous action, where exceptions are typically catched with a `try-catch` block. If it had been asynchronous, a callback would have been the way to go.

```js
var Mustache = require('mustache');

var view = {
  title: "Joe",
  calc: function () {
    return 2 + 4;
  }
};

try {
  console.log(Mustache.render("{{title}} spends {{calc}", view));
} catch (err) {
  console.error('Rendering crashed:', err.message)
}
```

**Comment by tvld** [comment]
Great reply. I've had a promise somewhere else, so indeed I will try and catch.. thank you :)

**Comment by phillipj** [comment]
Np, closing this issue for now.
