### ISSUE TITLE
Cannot find module on ubuntuGnome 16.04

### ISSUE THREAD

**Issue by fabpin** [janl/mustache.js#607]
thanks in advance for any help, im tried to run mustache, on a ubuntuGnome 16.04 with node.js v:4.6.0, npm v:2.15.9, mustache v:2.21.0, express v:4.14.0 and request v:2.75.0 dependecies installed, the version of each dependecies are below, but didnt work, somebady could help me pls ? 
mustache-test.js

`var Mustache = require("mustache");
Mustache.render("Hello, {{first}} {{last}}!", {
	first: "Nicolas",
	last: "Cage"
});
console.log(result);

Mustache.render("Hello, {{first}} {{last}}!", {
	first: "Sheryl",
	last: "Sandberg"
});`

`fabio@fabio-Aspire-4738:/media/fabio/Datos/Express/2_required_a_module$ npm list
mustache-test@0.0.1 /media/fabio/Datos/Express/2_required_a_module
├─┬ express@4.14.0
│ ├─┬ accepts@1.3.3
│ │ ├─┬ mime-types@2.1.12
│ │ │ └── mime-db@1.24.0
│ │ └── negotiator@0.6.1
│ ├── array-flatten@1.1.1
│ ├── content-disposition@0.5.1
│ ├── content-type@1.0.2
│ ├── cookie@0.3.1
│ ├── cookie-signature@1.0.6
│ ├─┬ debug@2.2.0
│ │ └── ms@0.7.1
│ ├── depd@1.1.0
│ ├── encodeurl@1.0.1
│ ├── escape-html@1.0.3
│ ├── etag@1.7.0
│ ├─┬ finalhandler@0.5.0
│ │ ├── statuses@1.3.0
│ │ └── unpipe@1.0.0
│ ├── fresh@0.3.0
│ ├── merge-descriptors@1.0.1
│ ├── methods@1.1.2
│ ├─┬ on-finished@2.3.0
│ │ └── ee-first@1.1.1
│ ├── parseurl@1.3.1
│ ├── path-to-regexp@0.1.7
│ ├─┬ proxy-addr@1.1.2
│ │ ├── forwarded@0.1.0
│ │ └── ipaddr.js@1.1.1
│ ├── qs@6.2.0
│ ├── range-parser@1.2.0
│ ├─┬ send@0.14.1
│ │ ├── destroy@1.0.4
│ │ ├─┬ http-errors@1.5.0
│ │ │ ├── inherits@2.0.1
│ │ │ └── setprototypeof@1.0.1
│ │ ├── mime@1.3.4
│ │ ├── ms@0.7.1
│ │ └── statuses@1.3.0
│ ├── serve-static@1.11.1
│ ├─┬ type-is@1.6.13
│ │ ├── media-typer@0.3.0
│ │ └─┬ mime-types@2.1.12
│ │   └── mime-db@1.24.0
│ ├── utils-merge@1.0.0
│ └── vary@1.1.0
├── mustache@2.2.1
└─┬ request@2.75.0
  ├── aws-sign2@0.6.0
  ├── aws4@1.5.0
  ├─┬ bl@1.1.2
  │ └─┬ readable-stream@2.0.6
  │   ├── core-util-is@1.0.2
  │   ├── inherits@2.0.3
  │   ├── isarray@1.0.0
  │   ├── process-nextick-args@1.0.7
  │   ├── string_decoder@0.10.31
  │   └── util-deprecate@1.0.2
  ├── caseless@0.11.0
  ├─┬ combined-stream@1.0.5
  │ └── delayed-stream@1.0.0
  ├── extend@3.0.0
  ├── forever-agent@0.6.1
  ├─┬ form-data@2.0.0
  │ └── asynckit@0.4.0
  ├─┬ har-validator@2.0.6
  │ ├─┬ chalk@1.1.3
  │ │ ├── ansi-styles@2.2.1
  │ │ ├── escape-string-regexp@1.0.5
  │ │ ├─┬ has-ansi@2.0.0
  │ │ │ └── ansi-regex@2.0.0
  │ │ ├─┬ strip-ansi@3.0.1
  │ │ │ └── ansi-regex@2.0.0
  │ │ └── supports-color@2.0.0
  │ ├─┬ commander@2.9.0
  │ │ └── graceful-readlink@1.0.1
  │ ├─┬ is-my-json-valid@2.15.0
  │ │ ├── generate-function@2.0.0
  │ │ ├─┬ generate-object-property@1.2.0
  │ │ │ └── is-property@1.0.2
  │ │ ├── jsonpointer@4.0.0
  │ │ └── xtend@4.0.1
  │ └─┬ pinkie-promise@2.0.1
  │   └── pinkie@2.0.4
  ├─┬ hawk@3.1.3
  │ ├── boom@2.10.1
  │ ├── cryptiles@2.0.5
  │ ├── hoek@2.16.3
  │ └── sntp@1.0.9
  ├─┬ http-signature@1.1.1
  │ ├── assert-plus@0.2.0
  │ ├─┬ jsprim@1.3.1
  │ │ ├── extsprintf@1.0.2
  │ │ ├── json-schema@0.2.3
  │ │ └── verror@1.3.6
  │ └─┬ sshpk@1.10.1
  │   ├── asn1@0.2.3
  │   ├── assert-plus@1.0.0
  │   ├── bcrypt-pbkdf@1.0.0
  │   ├── dashdash@1.14.0
  │   ├── ecc-jsbn@0.1.1
  │   ├── getpass@0.1.6
  │   ├── jodid25519@1.0.2
  │   ├── jsbn@0.1.0
  │   └── tweetnacl@0.14.3
  ├── is-typedarray@1.0.0
  ├── isstream@0.1.2
  ├── json-stringify-safe@5.0.1
  ├─┬ mime-types@2.1.12
  │ └── mime-db@1.24.0
  ├── node-uuid@1.4.7
  ├── oauth-sign@0.8.2
  ├── qs@6.2.1
  ├── stringstream@0.0.5
  ├── tough-cookie@2.3.1
  └── tunnel-agent@0.4.3
`

appear this error:
`fabio@fabio-Aspire-4738:/media/fabio/Datos/Express/2_required_a_module$ node mustache-test.js
module.js:327
    throw err;
    ^

Error: Cannot find module '/media/fabio/Datos/Express/2_required_a_module/mustache-test.js'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:974:3`

**Comment by phillipj** [comment]
Sorry for the late reply @fabpin!

The error you're seeing isn't because mustache.js isn't found, but that the script you're trying to execute (`mustache-test.js`) doesn't exist in the current directory.

E.g. if I try to run a script which doesn't exist I get the same error:

```bash
➜  node does-not-exist.js
module.js:457
    throw err;
    ^

Error: Cannot find module '/dev/does-not-exist.js'
    at Function.Module._resolveFilename (module.js:455:15)
```

Although, if the script exists, but the mustache.js dependency isn't found, this will be the error output:

```bash
➜  node existing-script.js
module.js:457
    throw err;
    ^

Error: Cannot find module 'mustache'
    at Function.Module._resolveFilename (module.js:455:15)
```

With that said, double check that you're in the correct directory before trying to execute a script. I'm closing this issue for now, feel free to re-open if you've got more questions.

**Comment by fabpin** [comment]
Thanks for response, but Thant is not true, already i run the following command:`npm install` and installed the package in the following uri: /home/fabio/Dcomentos/nustache/node_modules/mustache/mustache.js, but the automatic search uri didn't are taken by  node, just jump the error, i supposed than node realize the search first in node_module/mustache/mustache.js, for convention. but didn't do that

![captura de pantalla de 2016-10-16 16-48-38](https://cloud.githubusercontent.com/assets/8019419/19421246/f53c2b9c-93c1-11e6-9a65-c695e8c5c916.png)
![captura de pantalla de 2016-10-16 16-48-45](https://cloud.githubusercontent.com/assets/8019419/19421247/f53d68ae-93c1-11e6-8c24-71023b931cdc.png)
![captura de pantalla de 2016-10-16 16-48-51](https://cloud.githubusercontent.com/assets/8019419/19421248/f53eb100-93c1-11e6-9158-6bb562b0af66.png)

**Comment by fabpin** [comment]
i believe than is a error from node.js

**Comment by phillipj** [comment]
From the screenshots you've shown, the `mustache-test.js` script you're trying to execute, exists in a directory called `nustache`.

Although in the error output you pasted originally, you were standing in the directory `/media/fabio/Datos/Express/2_required_a_module` when you tried to execute `node mustache-test.js`. That will not work as that script is not in the `2_required_a_module` directory at all.

**Comment by fabpin** [comment]
aa ok, thanks, for the response, only work in the same directory, didnt search into the node_module for the required, thanks
