### ISSUE TITLE
function without closing tag?

### ISSUE THREAD

**Issue by jamesaspence** [janl/mustache.js#614]
Hi,

I was hoping to be able to call a function in mustache without a closing tag (as I have no need to pass content to it). I.e.:

`Here is my {{#templateFunc}} and it is great`

With `templateFunc` here retrieving values, parsing them slightly, and returning them (without a need to do a render). 

I was wondering if functionality that like is available, or if my best option is to just set variables in the data being passed in? i.e. `data.templateFunc = (12 * 3 + 6);`.

**Comment by dasilvacontin** [comment]
Hi @jamesaspence!

Yes, it is possible. Copy / pasting the [Usage](https://github.com/janl/mustache.js#usage) section from the README:

```js
var view = {
  title: "Joe",
  calc: function () {
    return 2 + 4;
  }
};

var output = Mustache.render("{{title}} spends {{calc}}", view);
```

Cheers!

**Comment by jamesaspence** [comment]
Ah, I missed that! Thank you, I feel dumb now.

**Comment by dasilvacontin** [comment]
No worries!

The README could be better structured, with emphasis on usage.
