### ISSUE TITLE
Question - Mustache as JSON templating?

### ISSUE THREAD

**Issue by WesTyler** [janl/mustache.js#623]
Hi there, we are looking at how we can potentially use mustache.js to facilitate templated JSON configurations within a Node app. Here's a simplified version of what we want to do, and how it's not working. Any input is appreciated.

The config to be loaded into the Node app
```json
{
    "foo": "{{bar}}"
}
```

```js
const template = JSON.stringify(require('./config'));
const context = {
    bar: {
        data: 'baz'
    }
};


const output = Mustache.render(template, context);
console.log('OUTPUT:', output);
```

#### What we expect
```js
OUTPUT: {"foo": {"data": "baz"}}
```

#### What we see
```js
OUTPUT: {"foo":"[object Object]"}
```

**Comment by phillipj** [comment]
What you're seeing is the `.toString()` representation of that object. In detail that happens because of the string concatenation in [Writer.renderTokens()](https://github.com/janl/mustache.js/blob/master/mustache.js#L496) method.

```js
const context = {
  bar: {
    data: 'baz'
  }
};

const barAsString = '' + context.bar;
console.log('OUTPUT:', barAsString);

// -> OUTPUT: [object Object]
```

Do achieve what you expect, I see two viable options:

```js
// #1
const context = {
  bar: JSON.stringify({
      data: 'baz'
  })
};

// #2
function Bar(data) {
  this.data = data
}

Bar.prototype.toString = function() {
  return JSON.stringify(this);
};

const context = {
  bar: new Bar('baz')
};
```

**Comment by WesTyler** [comment]
Thanks for the reply. :)

We were hoping to get around `JSON.stringify`ing the context data, but it looks more and more like we have no choice if we want to use templates like this, haha.

That does answer the question, so I'll go ahead and close this out. Thanks again.
