### ISSUE TITLE
get tag into javascript code

### ISSUE THREAD

**Issue by Clowning** [janl/mustache.js#624]
Hi there,

I'm using Mustache.JS for my project but i need to get a value into my JS code ! How can i get this value into my js (Is an external JS import not in the mustache) ? 

Thanks

**Comment by phillipj** [comment]
Hi!

An actual example of what you are trying to do would be very helpful for us, to help you ;)

**Comment by Clowning** [comment]
You right sorry ! :x 

when i call the template
`this.render(req, res, "m2choice/index", options);`

My template : 

```
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <title>title</title>
    <script>
//This solution work but it's not the good thing to do i think!
    const mobileId= "{{pocData.mobile.id}}"
    </script>

//I need to have my variable into these files ! 
    <script src="../../scripts/state.js"></script>
    <script src="../../scripts/logic.js"></script>
    <script src="../../scripts/listener.js"></script>

</head>

<body>
data
</body>
</html>
```

**Comment by phillipj** [comment]
Thx!

> Is an external JS import not in the mustache

No, it does not have functionality for importing other JS files or data, other than what is passed as  the second argument (`options` in your example).

mustache treats the template being rendered as a plain string. In other words it doesn't try to evaluate the contents of the .html file you pasted above, other than searching for the know mustache syntax to insert/replace text into the desired position in the final string.

Personally don't see any cleaner way of getting hold of `pocData.mobile.id` than what you've already done.

**Comment by phillipj** [comment]
Closing this for now, don't hesitate to re-open if you have more questions.
