### ISSUE TITLE
routes partials in common

### ISSUE THREAD

**Issue by roccomuso** [janl/mustache.js#625]
I'm using mustache with [consolidate](https://github.com/tj/consolidate.js/).
I have multiple routes using the same partials.
I wanna avoid having duplicate code, so I'm using a var containing the partials paths:

```javascript
var commonPartials = {
  head: 'partials/header',
  footer: 'partials/footer'
}

router.get('/hello', function (req, res) {
  res.render('hello', {
    partials: commonPartials,
    title: 'Hello',
    pid: process.pid
  })
})

router.get('/world', function (req, res) {
  res.render('world', {
    partials: commonPartials,
    title: 'World',
    pid: process.pid
  })
})
```

The issue is that on the second call of a route, the obj are populated with the whole partial file giving an error like this:

```
Error: ENOENT: no such file or directory, open '/home/user/Desktop/REPOS/HelloWorld/views/<footer class="footer">
  <div class="container">
    <div class="content has-text-centered">
      <p>
      ...
```

What's the best way to handle this issue and sharing partials to avoid duplicated code?

**Comment by phillipj** [comment]
Hi!

This is really a consolidate issue, as reading partials from a file is not something supported by the mustache.js package. That said, I've had a look at what might causing what you're seeing.

The me, the first thing that comes to mind when something works as expected the first time, but suddenly behaves differently the second time, is some code somwehere has changed (mutated) the object you pass around to other parts of your or 3rd party functions.

In this particular case, I had a close look at *everything* that reads or **writes** to the partials object you provide. And here's the parts inside consolidate that I suspect the most: https://github.com/tj/consolidate.js/blob/master/lib/consolidate.js#L124

To the interesting part, what can you do to avoid this happening? Not sharing the partials object (`commonPartials`), but creating a new partials object every time would probably work:

```js
// option 1
function commonPartials() {
  return {
    head: 'partials/header',
    footer: 'partials/footer'
  }
}

router.get('/hello', function (req, res) {
  res.render('hello', {
    partials: commonPartials(),
    title: 'Hello',
    pid: process.pid
  })
})

// option 2
function withPartials(viewData) {
  return Object.assign({
    partials: {
      head: 'partials/header',
      footer: 'partials/footer'      
    }
  }, viewData)
}

router.get('/hello', function (req, res) {
  res.render('hello', withPartials({
    title: 'Hello',
    pid: process.pid
  })
})
```

Hopefully that makes sense?

**Comment by roccomuso** [comment]
@phillipj Yeah i came with the same solution. Consolidate allows netsted partials that's why that variabiles are populated on the 2th call I guess.

**Comment by phillipj** [comment]
Good to hear you found a solution 👍
