### ISSUE TITLE
some suggestions

### ISSUE THREAD

**Issue by vopjie** [janl/mustache.js#628]
1，Is it possible to extend the if/else judgment?
2，Is it possible to add data index when data-repeat?

besause without these functions, most time i need to do more work with javascript.

**Comment by Romanx** [comment]
@vopjie This is probably best served over at [https://github.com/mustache/spec](https://github.com/mustache/spec) as it contains the spec of what mustache.js implements (along with other implementations in different languages). I will warn you that the spec hasn't been updated in many eons unfortunately.

If you want something less opinionated about logic in templates then you may be interested in http://handlebarsjs.com/ which is quite compatible with the mustache spec but has the features you requested.

Hope this helps

**Comment by vopjie** [comment]
ok,thansk
