### ISSUE TITLE
Scoping issues using nested selectors with same names.

### ISSUE THREAD

**Issue by Hodrobond** [janl/mustache.js#629]
Assuming the following object:

```
category.nodes = [
  {
    product: "1",
    type: "product"
  },
  {
    product: "2",
    type: "product"
  },
  {
    category: "categoryName",
    type: "category"
  }      
]
```
And the following template:

```
<p>
    {{#category.nodes}}
      {{#product}}
        <li>{{product}}</li>                            
      {{/product}}
      {{#category}}
        <li>{{category}}</li>
      {{/category}}
   {{/category.nodes}}
</p>
```

One would assume that one `<li></li>` would be made for the category, however 3 are made.
It appears to be referencing the parent `category` instead of the nested section `category`

[here](http://jsfiddle.net/wj94ao0o/3/) is a jsfiddle demonstrating the issue, and [here](http://jsfiddle.net/wj94ao0o/4/) is one demonstrating appropriate behavior by adjusting the parent name (category --> parent).

[Related question on StackOverflow](http://stackoverflow.com/questions/43530225/mustache-conditional-on-nested-sections-using-same-names)

**Comment by jwb** [comment]
This behavior matches [the specification](https://github.com/mustache/spec/blob/master/specs/interpolation.yml).

**Comment by Hodrobond** [comment]
Apologies, I must have missed that bit =(
Thank you for the response!
