### ISSUE TITLE
Compressing min file and saving 3.97 kb

### ISSUE THREAD

**Issue by MouadDB** [janl/mustache.js#631]
How about using http://jscompress.com for min file of mustache.js and saving 3.97 kb like this https://gist.github.com/MouadDB/85ee9695fc6565fcdc253504cb631323

**Comment by dasilvacontin** [comment]
Sure, feel free to PR and improve the build system that generates the minified file!

https://github.com/janl/mustache.js/blob/master/hooks/pre-commit#L25-L54
https://github.com/janl/mustache.js/blob/master/Rakefile#L27-L30

**Comment by MouadDB** [comment]
Closed
