### ISSUE TITLE
Last bit of conversation @janl missed  

### ISSUE THREAD

**Issue by helloNext292** [janl/mustache.js#632]
Hi,

Thanks for wasting my time. And here is the snapshot of our conversation before I was blocked. Please note that if you ever dared to do this in person when I was in high-school I would have beat you like dog. Let's just stay respectful as grown ups. And don't do this again. Thanks!

<img width="602" alt="rest1" src="https://cloud.githubusercontent.com/assets/28690455/26036599/0cc3f95c-38fe-11e7-9d1b-94157c0d5f18.png">

**Comment by cool88** [comment]
@janl

**Comment by helloNext292** [comment]
@janl see above. and DO not respond!

**Comment by phillipj** [comment]
Not related to this project.
