### ISSUE TITLE
Partials syntax {{> tpl}} is ecaped to {{&gt; tpl}} with element.innerHTML

### ISSUE THREAD

**Issue by ifgx** [janl/mustache.js#634]
Its not a direct Mustache bug, but it's caused by the browser/js encoding rule, but maybe it is necessary to say it in the documentation or add the support of this particular scenario:

When you retrieve HTML template with `element.innerHTML`, because the unique character` '>'` is not a valid HTML tag (as opposed of '`<tag>`' with opening and closing arrows), it gets HTML-encoded by JS or browser (idk). The result is, the syntax `{{> myPartial}}` then becomes `{{&gt; myPartial}}`, which is not parsed by Mustache.
There are two ways of making it work:
- Store your template in a string var, so it doesn't get html-encoded
- Replace the html-encoded character `'&gt;'` with` '>'` so you invert the unwanted processus. Note: mind the fact that if you replace all these characters, you might be also targeting non-Mustache characters and this may be a security issue.

See example of not working and working solution : https://jsfiddle.net/csuvrv8o/

**Comment by danielcobo** [comment]
I think this issue can simply be avoided by avoiding user generated partials (and escaping characters for partials you as the developer wrote yourself doesn't really make sense anyway).

You can avoid user generated partials by passing user generated data to be parsed within the partials That way you would be altering the partials based on user input in a safer way.

**Comment by bobthecow** [comment]
The right answer is to use a `<script>` tag and get the content with `innerText`. This preserves whitespace, lets you use mismatched tags, and keeps it from escaping things.

**Comment by ifgx** [comment]
Thanks for the tip @bobthecow. Actually, I tried and even `innerHTML` works when retrieving template whithin `<script id="my-template>` tags: it doesn't encode mismatched tags.

Downside of this method is you can't use embedded HTML template in your page. If you isolate your template in `<script>` tags, the browser will not be able to get and cache the resources in advance. It will have to wait the final Mustache Render execution to know which resources your HTML code is pointing to.

**Comment by dasilvacontin** [comment]
You could add some JS after the template declaration that adds an invisible DOM Element with the content of the template, so that it triggers the fetches of the resources, simulating what you used to have.

**Comment by dasilvacontin** [comment]
Closing since the Issue we are currently at ("Partials syntax ... is escaped ...") is solved by @bobthecow's tip. We can continue discussing your other issue here or on a new Issue.

Let us know if my comment was of any help!
