### ISSUE TITLE
Configure custom extension for partials lookup?

### ISSUE THREAD

**Issue by kristianmandrup** [janl/mustache.js#636]
Trying to use partials. In my project, files are named `.mst`. Is there a way to customize mustache to lookup partials by a custom extension instead of `.mustache` ??

**Comment by kristianmandrup** [comment]
Finally figured it out... 

```js
function _loadSharedPartials() {
    var partials = {};
    let rootDir = './editor/templates'
    var files = fs.readdirSync(rootDir);
    for (var i = 0, l = files.length; i < l; i++) {
        var file = files[i];

        if (file.match(/\.mst$/)) {
            var name = path.basename(file, '.mst');
            let filePath = path.resolve(rootDir, file)
            partials[name] = fs.readFileSync(filePath, 'utf8');
        }
    }

    return partials;
}
```

**Comment by phillipj** [comment]
Hi!

What other mustache related packages do you use in your project? This core
package has no sense of files at all, in other words reading templates from
files has to be provided from another package. Its that package that has to
be told which file extensions you're using.

Does that make sense?

**Comment by phillipj** [comment]
Good to hear you found a solution 👍

I'll add a friendly reminder that to using synchronous has a big performance hit, especially if it's done on every request since it blocks the thread. Running that on application boot should be just fine though.

**Comment by kristianmandrup** [comment]
None, was wondering why no such "load partial" solutions were mentioned or referenced in the docs? I'd have thought some of the common scenarios would be built in

**Comment by phillipj** [comment]
That is understandable.

My take on that is that this package is first and foremost a JavaScript implementation of the [mustache templates spec](https://mustache.github.io/mustache.5.html) and aims to work in both browsers and server environments. Speaking of browsers in particular, does not have access to the filesystem, therefore also something we don't have built directly into this package.

Usually one would use other packages such as [consolidate](https://www.npmjs.com/package/consolidate) that uses this core mustache.js package under the hood, but offers functionality valuable in a server environment. And doing it "by hand" as you have found is also a possibility of course.
