### ISSUE TITLE
If the view's like this: {"path": "/home/chalin"}

### ISSUE THREAD

**Issue by Chalin-Shi** [janl/mustache.js#648]
template: {"path": {{path}}}
If the view's like this: {"path": "/home/chalin"}
the result will: {"path": "\&#x2F;home\&#x2F;chalin"}

**Comment by phillipj** [comment]
That's intended. Mustache.js HTML escapes values by default, if you want to avoid that, use three curly braces ("mustaches"). Example template:

```
{ "path": {{{path}}} }
```

See https://mustache.github.io/mustache.5.html for more information about the syntax and behaviour.

Closing this for now, don't hesitate to re-open if this doesn't answer your question.

**Comment by rohitshetty** [comment]
Thanks for the answer!. It helped. Maybe this should goto readme?
