### ISSUE TITLE
How to run on a directory/folder of files?

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [janl/mustache.js#651]
Can this be supported? I.e. if a directory is passed (or, even better, a minimatch/glob wildcard path), all the files be processed?

**Comment by phillipj** [comment]
Not a bad idea, mind elaborating a bit more? I.e. a thought scenario of directory/file structure and a use case?

**Comment by JoshuaKGoldberg** [comment]
I have a directory of setup files (package.json, tslint.json, test/index.html, etc.) that get copied into a project during setup. Some have templates that should be filled out by mustache. 

To work around mustache only supporting one file at a time I'm using run-on-every-file to
run mustache once per file.

**Comment by JoshuaKGoldberg** [comment]
Closing out my old issues in repos that haven't had updates in a few years. Cheers!
