### ISSUE TITLE
Parse JSON Object from Document Store Database (NoSQL)

### ISSUE THREAD

**Issue by andreaslacza** [janl/mustache.js#654]
When you get follow Output in Node.js from a Document Store Database
Example (Output from Database value = Column with JSON Document for each row)
`[{`
`id: 3,`
`date: 2018-02-25T17:48:42.000Z,`
`value: '{"name": "User3", "username": "Username3", "gender": "Male"}' },`
`{`
`id: 2,`
`date: 2018-02-25T17:48:38.000Z,`
`value: '{"name": "User2", "username": "Username2", "gender": "Male"}' },`
`{`
`id: 1,`
`date: 2018-02-25T17:48:31.000Z,`
`value: '{"name": "User2", "username": "Username2", "gender": "Male"}'`
`}]`

you can't loop and parse/access and render the keys and values like:
`{{#users}}`
`{{name}} with {{id}} has {{username}} and has the Gender: {{gender}}`
`{{/users}}`
or
`{{#users}}`
`<p>{{value.name}} with {{id}} has {{value.username}} and Gender: {{value.gender}}</p>`
`{{/users}}`

**Comment by phillipj** [comment]
Closing this for now as there has been several valuable tips provided and the author hasn't replied.
