### ISSUE TITLE
Failed Set Href and Src

### ISSUE THREAD

**Issue by yudyananda** [janl/mustache.js#655]
I I found that the template inside `href` and `src` is not rendered as it should be. So i test it in another attibute like `class` and `id` the result is works like a charm.

I'm using Hugo so i have t wrap the mustache tempate with another curly braces,  here is my example code

```
<script type="text/html" id="hit-template">
  <div class="hit">
    <div class="hit-image">
      <img src="{{ "{{{image}}}" }}" alt="{{ "{{alt}}" }}">
    </div>
    <div class="hit-post">      
      <a href="{{ "{{permalink}}" }}">
      {{ "{{{_highlightResult.title.value}}}" }}
  	  </a>
      <p class="hit-description">{{ "{{{_highlightResult.summary.value}}}" }}</p>
    </div>
  </div>  
</script>
```

The question is how to make the template woking inside `href` and `src`?

**Comment by phillipj** [comment]
mustache.js treats everything as text, in other words it doesn't have a recollection of different HTML attributes and how to treat them differently from others.

Would you mind providing an example of what gets rendered and what you expect? Maybe we can help you with some thoughts of what seems to be happening..

**Comment by yudyananda** [comment]
I expect the mustache template render the value as it should be, from the example above mustache failed to render the value inside `href` and `src`, but and as you say after some trial I found that there is no recollection on HTML attributes. 

I finaly realize in Hugo (href and src)  I have to wrap the mustache in weird way than usualy. In case 
someone have the same experience (using Hugo and Mustache) here's the workaround

```
{{ safeHTML "<a href=\"{{permalink}}\">" }}	
```
@phillipj  thank you for answering my question.
