### ISSUE TITLE
Template validation support

### ISSUE THREAD

**Issue by bluzi** [janl/mustache.js#656]
Hey,

I think it'll be a good idea to add a function that retrieves a template and returns false if the template is invalid.
Some apps relay on user content and that's a good reason to choose a "logic-less" template engine, but when relaying on user content you can't just assume the template is valid.
I know you can achieve the same result using `render` with try catch, but it's not as convenient and won't be as efficient in situations where you just want to validate the template without actually rendering it.

Here's what I had in mind:
```js
if (Mustache.isValid(template)) {
     const result = Mustache.render(template, {hello: 'world'});
} else { 
     console.error('Template is invalid');
}
```

**Comment by belauzas** [comment]
Looks like a great idea!

**Comment by phillipj** [comment]
Sorry for not responding to this earlier! That was really disrespectful for your good intention of contributing to this project.

Our main focus is to ensure mustache.js implements the [mustache spec](https://mustache.github.io/) correctly. Other than that, we're not motivated to adding extra functionality, even though it would be really convenient. To me personally it boils down to the lack of maintainers, as shown by you not getting an answer after 1.5 years, and the fact that adding things also means more maintenance as time goes by.

Therefore closing this for now, as it _is_ strictly possible with a `try-catch` when invoking `Mustache.render()` as you mention.
