### ISSUE TITLE
Problem with custom delimiters

### ISSUE THREAD

**Issue by nkcjs** [janl/mustache.js#659]
|   Setting            |  Anticipant        |   Result    |
|------------------|------------------|------------|
| {{=<% %>==}} |      <%   %>=     |  <%  %> |

![image](https://user-images.githubusercontent.com/22137828/39612473-73095be8-4f92-11e8-9246-b023591c1036.png)

change to

```js
if (type === '=') {
  value = scanner.scanUntil(closingTagRe);
  if (value.charAt(value.length - 1) !== '=')
    throw new Error('Setting in template failure');
  value = value.slice(0, -1).trim();
}
```

**Comment by scwong93** [comment]
I've submitted PR for this

**Comment by phillipj** [comment]
As the support for custom delimiters got improved late 2018 in https://github.com/janl/mustache.js/pull/643 and subsequent PRs, this bug needs to be re-tested before considering a plausible fix.

**Comment by phillipj** [comment]
Closing this for now due to lack of response from issue author. If it indeed still is an issue for what you're trying to do, don't hesitate re-opening the issue for further investigation.
