### ISSUE TITLE
How to get the object value of the selected item in select?

### ISSUE THREAD

**Issue by jofftiquez** [janl/mustache.js#660]
**data**

    {
      "data": {
        "cats": [
          {
            "name": "Kidlat",
            "age": 1
          },
          {
            "name": "Lanaya",
            "age": 2
          },
          {
            "name": "Akasha",
            "age": 2
          }
        ]
      }
    }

I have an `<select>` looped using mustache like: 

    {{#data.cats}}
    <select id="select">
      <option value="{{this}}">{{name}} - {{age}}</option>
    </select>
    {{/data.cats}}

The loop is working fine, however, I can't seem to get the object value of the item. 

    $('#clinicSelectMap').on("change", function(e) {
      console.log(this.value); // has value
      console.log(this.value.name); // undefined
    });

**Comment by peter-veres** [comment]
`this.value` contains only value of option, you have to get the `name` from the original `data`. Put the data you provided to view to separate variable, then you can use something like `view_data['data']['cats'][this.value]`

**Comment by jofftiquez** [comment]
Hi @peter-veres I got it working now. Sorry I didn't closed it soon after. Thanks!
