### ISSUE TITLE
Disappearing whitespace.

### ISSUE THREAD

**Issue by jeffv** [janl/mustache.js#67]
Input:
{{#rooms}}{{#bedrooms}}{{total}} {{/bedrooms}}    BED {{#bathrooms}}{{full}}{{/bathrooms}}{{/rooms}}     BATH

1BED 2BATH

Input: 
{{#rooms}}{{#bedrooms}}{{total}} {{/bedrooms}}BED    {{#bathrooms}}{{full}}     {{/bathrooms}}{{/rooms}}BATH

Output:
1     BED 2     BATH

Basically, if the white space is inside the {{#var}}{{/var}} it outputs correctly. If the whitespace trails it's trimmed off.

**Comment by wilfredor** [comment]
I have the same problem, 
hi:"hi",peter:"peter"

input:
{{hi}} {{peer}}

is rendered how:
hipeter

expected:
hi peter
