### ISSUE TITLE
Render method should take tags

### ISSUE THREAD

**Issue by raymond-lam** [janl/mustache.js#672]
The `parse` takes a `tags` argument, which overrides `mustache.tags`. There is no way to pass in a `tags` argument into the `render` method, however. In addition to the unfortunate asymmetry that this causes, this has caused some amount of confusion/concern with regard to the caching behavior of `parse`. See issue #669 for more discussion.

**Comment by raymond-lam** [comment]
The more I think about this, the more I am in favor of the changes proposed here and in issue #669. Using `parse` as a means of permanently overriding `Mustache.tags` for a particular template violates the Single Responsibility Principle; `parse` should take a template and some arguments (namely `tags`) and parse accordingly -- thats it.

Adding `tags` to `render` to "compensate" in conjunction with this change brings us closer to Least Astonishment: `render` will render according to the template and arguments it is given, and `Mustache.tags` if it is not overridden by such arguments. The arguments and `Mustache.tags` are totally transparent to the caller. More Astonishing would be `render` behaving depending on the template, arguments, and maybe `Mustache.tags` unless an opaque/hidden value was set by calling a different method (`parse`) whose original purpose wasn't to override `Mustache.tags` for all subsequent `render` calls.

Thanks to @mbrodala and @ilkovich for suggesting this.

**Comment by phillipj** [comment]
Couldn't agree more with your rationale above. Glad you've found an improvement that doesn't require the using developers to grasp the interconnection between `.render() | .parse() | .tags` 👍
