### ISSUE TITLE
Custom tags are not working for partials

### ISSUE THREAD

**Issue by stackchain** [janl/mustache.js#678]
If you use custom tags like <% it works only for the template main file, all partials inside don't keep this configuration, the partials only work with the standard tag {{.

Template
{
 my_hi_message: "hi",
 my_hi_message_2: "yo"
}

File1.txt
<% my_hi_message %>
<%> my_partial_file.txt %>

My_Partial_File.txt
<% my_hi_message_2 %> 

Output: 
hi
<% my_hi_message_2 %> 

---- If I keep the original tag {{ inside partials it works, it looks like subRender problem.
File1.txt
<% my_hi_message %>
<%> my_partial_file.txt %>

My_Partial_File.txt
{{ my_hi_message_2 }}

Output:
hi
yo

**Comment by phillipj** [comment]
v3.0.1 just got published including your fix in #679.

Thanks again!
