### ISSUE TITLE
How to use srcset

### ISSUE THREAD

**Issue by StanislavMayorov** [janl/mustache.js#680]
Hi. Is it possible to use img `srcset` attribute? I use this template and data. 
`<img class="sad_face" srcset={{sad_face_srcset}}>`
`data: "img/picture-sad.png 132w, img/picture-sad@2x.png 264w"`
But html output looks like this:
`<img class="sad_face" srcset="img/picture-sad.png" 132w,="" img&#x2f;picture-sad@2x.png="" 264w="">`

**Comment by phillipj** [comment]
Hi @StanislavMayorov,

what you're seeing here is the default HTML escaping of mustache as described in the [Variables section](https://github.com/janl/mustache.js#variables). If you want to explicitly avoid that safety, you can use triple mustaches: `{{{ sad_face_srcset }}}`.

Does that answer your question?

**Comment by StanislavMayorov** [comment]
Yes. Thank you.
