### ISSUE TITLE
inverted section: Intentional or bug

### ISSUE THREAD

**Issue by nssang00** [janl/mustache.js#681]
"first": '', 
"first": 0,
"first": '0'
"first": false
-> inverted section ok
 
If there is no value at all?
first no value(undefined) results?

**Comment by phillipj** [comment]
Not entirely sure I understand your question, maybe the section of falsy values and lists in the README answers your question?

> If the `person` key does not exist, or exists and has a value of `null`, `undefined`, `false`, `0`, or `NaN`, or is an empty string or an empty list, the block will not be rendered.

https://github.com/janl/mustache.js#false-values-or-empty-lists

**Comment by nssang00** [comment]
InvertedSection
If section equals false or is an empty list, the whole block will be rendered;
If section is non-false or a non-empty list, it won't be rendered.

If the person key does not exist, or exists and has a value of undefined, the block will not be rendered  or will be rendered.(?)
