### ISSUE TITLE
how to use mustache in angular applications

### ISSUE THREAD

**Issue by prashant1620** [janl/mustache.js#686]
how to use this mustache template in angular applications ???

**Comment by phillipj** [comment]
Hi!

Would you mind sharing your motivation for using mustache.js in Angular?

It's surely doable, though unclear to me why one would want that since Angular has its own templating engine built-in. Wouldn't surprise me if there's a good use case for it that I don't know about though 😄

**Comment by prashant1620** [comment]
Hi ,
thanks for reply,
         i have requirement like that , in json data will display on angular html using mustache template

**Comment by abdulkareemnalband** [comment]
Stick with angular template. as it provides more than just rendering data
It also handles updates when your data changes .

That said you can use `mustache.js` in you application if requirement demands
run following commands to add both mustache package and mustache typings
```sh
yarn add mustache
yarn add -D @types/mustache
```
or 
```sh
npm install  mustache --save
npm install @types/mustache --save -D
```
and in your `typescript` file

```ts
// in top
import * as Mustache from 'mustache'

// and some where in file use
Mustache.render(template, data, partial)

```

**Comment by prashant1620** [comment]
thank so much ,
Now its working....

**Comment by soscler** [comment]
In my case, I have a huge html template that I should pass to quilljs to show in the editor. It will be simpler to write the template once and let mustache render it with the actual values.

**Comment by soscler** [comment]
I have this error when I use mustach in angular ` ERROR in node_modules/@types/mustache/index.d.ts(362,6): error TS2456: Type alias 'TemplateSpans' circularly references itself.`

I have the following versions:
- Angular: 8.2.14
- Mustache: 4.0.1
- @types/mustache: 4.0.1

**Comment by phillipj** [comment]
@soscler as raised https://github.com/janl/mustache.js/issues/763#issuecomment-702900383, I get a hunch that's caused by an outdated TypeScript version.
