### ISSUE TITLE
How count n elements in json?

### ISSUE THREAD

**Issue by arcaela** [janl/mustache.js#687]
Have some tag to count elements?
`list = [1,2,3,4,5,6];`
To insert counts list in html?

**Comment by abdulkareemnalband** [comment]
You have to pre calculate and pass as a value

**Comment by phillipj** [comment]
You can use `{{list.length}}` in template to display how many items there are in that `list` array.

**Comment by piratadelfuturo** [comment]
Is there a way to know the index in the current loop position?

**Comment by abdulkareemnalband** [comment]
@piratadelfuturo Not that i know of but you can pass a new array of object with index and value as properties

ex:
instead of
```
{
data:{
list:[a,c,v]
}
}
```

pass
```
{
data:{
list:[{index:0 , value:a},{index:1,value:c}]
}
}
```

**Comment by raphaelkieling** [comment]
I use that, @abdulkareemnalband had a nice ideia. 
```js
function putIndexInArray(array){
	let putIndex = (value, index ) => {
  	return {
    	index,
      value
    }
  }
	return array.map(putIndex)
}


Mustache.render(template, {
    	array:putIndexInArray([1,2,3])
});
```

and i use 

```
{{#array}}
    	{{value}}
{{/array}}
```

**Comment by fernandoval** [comment]
> I use this, @abdulkareemnalband had a nice ideia.
> 
> ```js
> function putIndexInArray(array){
> 	let putIndex = (value, index ) => {
>   	   return {
>     	      index,
>               value
>            }
>         }
> 	return array.map(putIndex)
> }
> 
> 
> Mustache.render(template, {
>     	array:putIndexInArray([1,2,3])
> });
> ```
> 
> and i use
> 
> ```
> {{#array}}
>     	{{value}}
> {{/array}}
> ```

I'm using a variant from your method.

```js
const putIndexInArray = array => {
    let putIndex = (value, index) => {
        value['@index'] = index;

        return value;
    };

    if (!Array.isArray(array)) {
        return array;
    }

    return array.map(putIndex);
};

Mustache.render(template, {
    array: putIndexInArray(['Homer', 'Marge', 'Lisa'])
});
```

and then using like this:

```
{{#array}}
    {{@index}}
{{/array}}
```
