### ISSUE TITLE
Can i call a function from inside mustache templates which takes parameters ?

### ISSUE THREAD

**Issue by TusharRoy23** [janl/mustache.js#690]
//user_helper.js
<pre>
<code>
const User = require("../models/User");
var users = {
  getUserInfo: function(userID) {
    var query = { _id: userID };
    User.findById(query)
      .then(user => {
        return user;
      })
      .catch(err => {
        res.json({
          confirmation: "failed"
        });
      });
  }
};
module.exports = users;
</code>
</pre>
// index.js
<pre>
<code>
router.get("/home", (req, res) => {
  Profile.find()
    .then(profile => {
      res.render("index", {
        userID: req.session.userID,
        helper: require("../helpers/user_helper")
      });
    })
    .catch(err => {
      res.status(400).send("Unable to fatch");
    });
});
module.exports = router;
</code>
</pre>
// Index.mustache
<code>
<pre>
<p>
	{{ how can i show value by calling function which is locate in user_helper }}
</p>
</code>
</pre>

**Comment by nizarilyas10p** [comment]
any update on it ?

**Comment by Mr-jiangzhiguo** [comment]
I got the same question, are you solve it ?

**Comment by TusharRoy23** [comment]
Actually i haven't found exact solution yet. But i found a solution for it. I was using Express JS that's why i came up with this solution. Please check out this link [express-hbs](https://www.npmjs.com/package/express-hbs).
Thank you.

**Comment by Mr-jiangzhiguo** [comment]
ok, use `handlebars` instead of `mustache`
