### ISSUE TITLE
Why does mustache escape by default?

### ISSUE THREAD

**Issue by goldingdamien** [janl/mustache.js#695]
I find myself always disabling escaping which makes me think I am doing something wrong.
Is taking an html template and passing data wrong?
I thought that the escaping is for user input data from a DB, but that would mean only escaping the input data, not the entire html.
What is the correct method for rendering with escaping enabled and why?

**Comment by phillipj** [comment]
I've done the exact opposite throughout the years, very rarely disable escaping 😃 

Mind providing a concrete example or two of what you usually end up doing? Including the template(s) and data you're passing.

**Comment by goldingdamien** [comment]
I haven't gone deeply into the issues so I guess my issue probably arises from nested templates.
Escaping in Mustache is on the object data only?
If the above is correct, what is the recommended way for nested templates?

**Comment by phillipj** [comment]
Nested (read [partial](https://github.com/janl/mustache.js#partials)) templates doesn't affect escaping of values put into templates, so I would still appreciate getting some hands-on examples of where double escaping is an issue.

**Comment by goldingdamien** [comment]
I was not using partials.
I had nested data being rendered by mustache separately and being passed as data.
For example:

```
<!--PARENT TEMPLATE-->
<div>
<div>{{title}}</div>
{{TEMPLATE_child}}
</div>

<!--CHILD TEMPLATE-->
<div>
Child text
</div>

mustache.render(parentHTML, {
title: 'my title',
TEMPLATE_child: mustache.render(childHTML, {})
})
```

**Comment by phillipj** [comment]
Ahhh, thanks!

Have you tried giving partials a shot? That's the way mustache.js has solved nested templating, and would avoid the need to disable the default HTML escaping at a regular basis.

**Comment by goldingdamien** [comment]
I'll give them a go. Thanks.
I'll close the issue.
