### ISSUE TITLE
Need setter for escape

### ISSUE THREAD

**Issue by busheezy** [janl/mustache.js#697]
Is it possible to get a setter for the escape function? There might be a better way. I'm running into issues with TypeScript.

https://share.busheezy.dev/SovaRs

Thanks.

**Comment by danecreekphotography** [comment]
Agreed I'm hitting this issue too. I can't override using the sample in the documentation because Typescript says it is a read-only property.

**Comment by danecreekphotography** [comment]
I thought I hit this too but I figured out that it isn't necessary. Import Mustache like this:

```typescript
import Mustache from 'Mustache';
```

Then override escape() like this:

```typescript
  Mustache.escape = text => {
    return text;
  };
```

**Comment by phillipj** [comment]
Thanks for chiming in @danecreekphotography 👍 

As far as I can see, `Mustache.escape` is not marked as `readonly` in the latest [`@types/mustache/index.d.ts`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/mustache/index.d.ts#L57) at least.

@busheezy any chance you're using old type definitions?

**Comment by phillipj** [comment]
Closing this for now as it doesn't seem like this is still an issue for you.
