### ISSUE TITLE
Template loaded from package.json : variables to partials

### ISSUE THREAD

**Issue by danielrsantana** [janl/mustache.js#702]
I'm working with MustacheJS to provide a static and super fast solution for some application and I would like to pass data to a generic partial that doesn't knows which data to access. 

Right now what I have is a simple environment (described bellow) and I'm using the mustache CLI configured in my package.JSON file to build the page I would like to consume. For best performance, this is a good strategy as in the first phase I won't have any dynamic generated data. 

Bellow follows what I've build so far and I'm having trouble accessing the JSON file with data when using it to build a generic component (HTML select element).

## Context

I've developed one generic select partial and would like to pass it's data by parameters (or any other way) in order to generate my static pages. 

I expected the helpers from Handlebars work but it isn't and I need some understanding if it's possible or not and what is the best way to achieve what I'm looking for.

## Process

Steps to reproduce:

1. **matchcenter.json**

```
{
    "competitionList": [
      {
        "value": "All",
        "text": "All Options"
      },
      {
        "value": "sample",
        "text": "Some Sample"
      }
    ],
    "seasonList": [
      {
        "value": "0",
        "text": "option1"
      },
      {
        "value": "1",
        "text": "option2"
      }
    ]
}
```

2. **package.json**

```
{
    "name": "app-name",
    "version": "1.0.0",
    "description": "some description",
    "scripts": {
        "build": "mustache ./assets/json/matchcenter.json -p ./src/partials/main.mustache -p ./src/partials/navigation/navigation.mustache -p ./src/partials/matchcenter/matchcenter.mustache -p ./src/partials/match/match.mustache -p ./src/partials/select/select.mustache ./src/index.mustache > ./src/index.html",
        "start": "webpack-dev-server --hot --config=webpack/dev.webpack.config.js"
    },
    "keywords": [],
    "author": "some author",
    "dependencies": {
        "@babel/core": "^7.4.5",
        "@babel/polyfill": "7.4.4",
        "@babel/preset-env": "^7.4.5",
        "babel-loader": "^8.0.6",
        "express": "^4.17.1",
        "handlebars": "4.1.2",
        "mini-css-extract-plugin": "^0.7.0"
    },
    "devDependencies": {
        "copy-webpack-plugin": "^5.0.3",
        "css-loader": "^3.0.0",
        "html-loader": "^0.5.5",
        "html-webpack-plugin": "^3.2.0",
        "mini-css-extract-plugin": "^0.7.0",
        "mustache": "3.0.1",
        "node-sass": "^4.12.0",
        "sass": "^1.21.0",
        "sass-loader": "^7.1.0",
        "source-map-loader": "^0.2.4",
        "style-loader": "^0.23.1",
        "uglifyjs-webpack-plugin": "^2.1.3",
        "webpack": "^4.34.0",
        "webpack-cli": "^3.3.4",
        "webpack-dev-middleware": "^3.7.0",
        "webpack-dev-server": "3.7.2",
        "webpack-hot-middleware": "^2.25.0",
        "webpack-merge": "^4.2.1"
    }
}

```

3. **index.mustache**
```
<html>

<head>
    <title>Sample</title>
    <link rel="stylesheet" type="text/css" href="css/fonts.css" media="all" />
    <link rel="stylesheet" type="text/css" href="css/styles.css" media="all" />
</head>

<body>
    <div class="header">
        <img src="../assets/images/mock-header.png" />
    </div>

    <div class="container">
        {{> main }}
    </div>
</body>

</html>
```

4. **navigation.mustache**
```
    <div class="navigation" id="navigation">
        <div class="navigation__competitions">
            {{> select list=competitionList}}
        </div>

        <div class="navigation__schedule">
            {{> select list=seasonList}}
        </div>
    </div>
```

5. **select.mustache**
```
<select class="select">
{{#list}}
  <option class="select__item" value="{{value}}">{{text}}</option>
{{/list}}
</select>
```

## Expected result

The expected result is two selects with the data from the JSON file. 

## Current result

The file is loaded and if I loop thought the variable names, the data is present. But when I try to pass it the way I found described in handlebars.js, the parse won't happen and nothing is rendered. The select element don't even appear if I pass something to the partial. 

The ways I tried to do it and I had the same result were:

```
{{> select list=seasonList}}
{{> select list:seasonList}}
{{> select seasonList}}
{{> select { list: seasonList} }}
{{> select { "list": seasonList} }}
```

Kind regards and thank you. 
Daniel Santana

ps: If I missed some information, please let me know.

**Comment by phillipj** [comment]
Hi @danielfagerstrom,

I noticed from your initial issue description, that it seemed like you were trying to send arguments to partials in a props-like manner which one often sees in React.js components and similar. In short, passing explicit arguments like that is not supported by mustache's partials.

Personally like the description found in the [official mustache docs about partials](http://mustache.github.io/mustache.5.html#Partials):

> .. you may want to think of partials as includes, imports ..

This resonates to me in the way that the partials get a hold of the same variables that are available where the partials are being used.

When trying to create a re-usable partial which iterates through an array of items, this can look a little weird at first due to the hash-period-combination `{{#.}} ... {{/.}}`, it just takes time getting used to reading or else it can be improved by restructuring the data passed into the template for rendered a bit.

Here's how using such a partial would look like conceptually:

```js
const template = `
  <div class="mmgr-navigation__competitions">
    {{#competitionList}}
      {{> select }}
    {{/competitionList}}
  </div>

  <div class="mmgr-navigation__schedule">
    {{#seasonList}}
      {{> select }}
    {{/seasonList}}
  </div>
`

const selectPartial = `
  <select class="mmgr-select">
    {{#.}}
      <option class="mmgr-select__item" value="{{value}}">{{text}}</option>
    {{/.}}
  </select>
`

const output = Mustache.render(template, data, { select: selectPartial })
```

I created a jsfiddle for a complete example: https://jsfiddle.net/ks7q06yf/7/. It looks a little different since this example runs in the browser, rather than via the CLI, but the template & partial contents is still the same between the two.

Shout if you're still not able to make that work for you.

**Comment by danielrsantana** [comment]
Thank you very much Phillip Johnsen, your explanation and example ensured what I realized after reading the library code.

From the way I see and as I can only use the CLI, better to skip generic components and if I need to do some data transformation or special selection on the data, I run a nodeJS script before.

Thank you very much for your time and help.

Kind regards,
Daniel Santana
