### ISSUE TITLE
Is there any option to show any default value when there is no corresonding value defined for a variable ?

### ISSUE THREAD

**Issue by gopesh67** [janl/mustache.js#707]

**Comment by KnutRyagerInmeta** [comment]
What I did was generate an interface for each of my template, and an object for the interface containing all default values. So I would just base my models on my default model.

Like this:

```
export interface TsFileTemplate {
	imports: ImportTemplate[];
	statements: TsFileStatementTemplate[];
 }
export function getTsFileTemplate() {
	return {
		imports: [] as ImportTemplate[],
		statements: [] as TsFileStatementTemplate[],
	} as const;
}
```

**Comment by phillipj** [comment]
mustache does not have a way of defining a default fallback value in the templates. This has to be done in the provided `view`.

What comes to mind to do this is either:

1. do the fallback check and insert an actual value into the `view` when it is created *before* asking mustache.js to render a template
2. create a utility [mustache function](https://github.com/janl/mustache.js#functions) that either returns the provided value when it's there, or use a fallback value when needed

It basically comes down to how & where you want to do the decision about whether or not to use a default value.

**Comment by simlu** [comment]
Here is a workaround. Note that it has some limitations:

```js
const render = (template, data) => {
  const proxyFactory = (obj) => new Proxy(obj, {
    get(target, name) {
      const r = obj?.[name];
      if (r === undefined) {
        return '<Not Specified>';
      }
      if (r instanceof Object) {
        return proxyFactory(r);
      }
      return r;
    },
    has() {
      return true;
    }
  });
  return Mustache.render(template, proxyFactory(data));
};
```
