### ISSUE TITLE
use value from list based on another value

### ISSUE THREAD

**Issue by karlismelderis** [janl/mustache.js#710]
Hello, Everyone

Sorry if the question is already answered somewhere or it's too trivial.
I'm looking for a way to use a value from the list based on another value
e.g.
```javascript
system: {
latest: v2
}

systems: {
v1: {
item: 1
},
v2: {
item: 111
}
}
```
and in markdown:
```javascript
{{systems.{{system.latest}}.item}}
```
:) syntax doesn't work but I hope it will help to show where I'm heading.

**Comment by phillipj** [comment]
Hi there,

sorry for the late reply!

That's one of those things that cannot be done in mustache templates, it's part of that sacrifice of "logicless templates" mantra.

In other words, you will have to prepare the data your giving to mustache *before* rendering the template. Continuing on the data you provided yourself:

```javascript
system: {
  latest: v2
}

systems: {
  v1: {
    item: 1
  },
  v2: {
    item: 111
  }
}

latestSystem: systems[system.latest]
```

And then use `{{latestSystem.item}}` in your template.

Does that make sense?

**Comment by phillipj** [comment]
Closing this for now due to lack of response from issue author. Don't hesitate to re-open if my answer didn't answer the question.
