### ISSUE TITLE
An inline partial should not be indented

### ISSUE THREAD

**Issue by hail2u** [janl/mustache.js#715]
The content of an inline partial is indented in v3.0.2 (of course not in v3.0.1). People does not want these extra white spaces in an HTML file.

test.json:

```json
{}
```

test.mustache:

```mustache
    <div>{{> partial}}</div>
```

partial.mustache:

```mustache
This is a partial.
```

Run:

```bash
$ mustache -p partial.mustache test.json test.mustache
    <div>    This is a partial.</div>
```

**Comment by phillipj** [comment]
Thanks for reporting!

I for sure agree your example looks both weird and unexpected. Without digging deep into how this could be solved in this project, I'm starting to get curious how other mustache implementations (java, PHP etc) handles indentation of partials.

The expected (or shall we say sensible) output of your example would be great to have as an unit test inside [./test/partial-test.js](https://github.com/janl/mustache.js/blob/master/test/partial-test.js).

**Comment by phillipj** [comment]
@yotammadem you got any thoughts on this by any chance?

**Comment by yotammadem** [comment]
I will take a look at this soon. Strange that the partials spec does not test it

**Comment by yotammadem** [comment]
This is strange..
When I tried to reproduce this with a unit test:
```
    it('Inline partials should not be indented', function () {
      var template = '"    <div>{{> partial}}</div>"';
      var data = {};
      var partials = {'partial':'This is a partial.'};
      var expected = '"    <div>This is a partial.</div>"';
      var renderResult = Mustache.render(template, data, partials);
      assert.equal(renderResult, expected);
    });

```
The unit test passed..
I will try with the command line

**Comment by yotammadem** [comment]
Ok, it was my mistake, when I ran this test, it failed:
```
it('Inline partials should not be indented', function () {
      var template = '    <div>{{> partial}}</div>';
      var data = {};
      var partials = {'partial':'This is a partial.'};
      var expected = '    <div>This is a partial.</div>';
      var renderResult = Mustache.render(template, data, partials);
      assert.equal(renderResult, expected);
    });
```

**Comment by yotammadem** [comment]
@phillipj  Take a look at: https://github.com/janl/mustache.js/pull/716
