### ISSUE TITLE
Are "sections" the way to do conditional rendering?

### ISSUE THREAD

**Issue by sproutwp** [janl/mustache.js#719]
Thank you for Mustache. It's been a great help but as the scope of my project grew, so did my requirements. I'm now looking to do some easy work without React where I need to have conditional rendering.

Here's how my data looks exactly, coming back from the server:

```
attachment: {
    title: Attachment,
    slug: attachment,
    state: {
        installed: true,
        active: false
    }
},
post: {
    title: Post,
    slug: post,
    state: {
        installed: true,
        active: true
    }
},
```

For each one of these items, I render a `<li>` containing the details but **depending on its [key].state.installed/active, I might choose to render it different or even show some buttons.** For example, if an item comes back with the `active: false, installed: true` state, I will have to hide the install button and instead show the activate one.

How can I tell Mustache that I want it to do this?

**Comment by phillipj** [comment]
Yes, _sections_ and _inverted sections_ is the way to go for both:

- iterating through an array
- conditionals

Have you read through our docs for [sections](https://github.com/janl/mustache.js#sections) and [inverted sections](https://github.com/janl/mustache.js#inverted-sections) or given them a shot?

**Comment by phillipj** [comment]
Closing this for now due to lack of response from the issue author. Don't hesitate to re-open if more explanation than what could be found in the mentioned docs would be helpful.
