### ISSUE TITLE
YAML Support?

### ISSUE THREAD

**Issue by jonioni** [janl/mustache.js#721]
As shown in [MUSTACHE(1)](https://mustache.github.io/mustache.1.html):

```bash
$ mustache data.yml template.mustache
```

**Comment by phillipj** [comment]
Hi, that's a good question!

Personally haven't considered the command line tool described there as part of the mustache spec, also underlined by the fact that quite a few mentions of `Ruby` being mentioned there.

As this project's command line tool only supports JSON, any YAML has to be transformed into JSON _first_. One way to do that is to use something like [yamljs](https://www.npmjs.com/package/yamljs) (or any tool that transforms YAML into JSON and writes it to stdout:

```
$ cat data.yml
name: chris

$ cat template.mustache
Hi {{name}}

$ yaml2json data.yml | mustache - template.mustache
Hi chris
```

Does that answer your needs?

**Comment by jon-certik** [comment]
Thanks for clarification @phillipj !

**Comment by phillipj** [comment]
Closing this for now, don't hesitate to re-open if you still got questions.
