### ISSUE TITLE
Consider refactor with TypeScript?

### ISSUE THREAD

**Issue by urain39** [janl/mustache.js#729]
```ts
const enum TokenMember {
    TYPE = 0,
    VALUE,
    ...
}

token[TokenMember.TYPE]
```
It's much better than such as `token[0]`, `token[1]`.

**Comment by phillipj** [comment]
Thanks for letting us know it would be valuable to make this package more TypeScript friendly.

Although I won't promise if it will be converted to TypeScript or expose TypeScript type definitions out the box later, I can say that it's a natural discussion to have as soon as currently open PR for transitioning to an ES module gets merged: https://github.com/janl/mustache.js/pull/728

**Comment by phillipj** [comment]
Thought you might be interested in knowing that it's planned to keep [@types/mustache](https://www.npmjs.com/package/@types/mustache) from DefinitelyTyped as up-to-date as possible going forward. Just added a section referencing that in our README: https://github.com/janl/mustache.js/commit/3bdd27c4e762f665232dc46186c7639e60dbd70e.

You're of course more than welcome to contribute with improvements to those type definitions.

**Comment by urain39** [comment]
Ok, thanks reply.
