### ISSUE TITLE
loop through all attributes

### ISSUE THREAD

**Issue by jeanpommier** [janl/mustache.js#734]
Hi,
In freemarker templates, one can easiliy loop through available values this way:
```
<#list feature.attributes as attribute>
      <td>${attribute.value}</td>
  </#list>
```
Is there a similar way using Mustache ?

My issue is I'm having some objects with year keys. As new years pass by, I'll have more year keys, so I don't want to hard code them, but I'd like to pass their values for use in a graph.

**Comment by phillipj** [comment]
Hi there!

Iterating through an object is not possible in mustache.js. It will have to be converted to an array first. Here's a small example from the top of my head that illustrates how that could be done:

```js
const dataPerYear = {
  2018: {
    title: 'Twenty eighteen'
  },
  2019: {
    title: 'Twenty nineteen'
  }
};

const yearsAsArray = Object.keys(dataPerYear).map(year => {
  const dataForYear = dataPerYear[year];

  return {
    year: year,
    data: dataForYear
  };
})

const template = `
  <ul>
  {{#years}}
    <li>{{year}}: {{data.title}}</li>
  {{/years}}
  </ul>
`;

const result = Mustache.render(template, { years: yearsAsArray });
```

https://jsfiddle.net/w2nL7xz0/

As far as I remember, [handlebars](https://handlebarsjs.com/) allows iteration on objects if that's a requirement you have and you don't want to perform the data preparation shown above.

Does that make sense?

**Comment by jeanpommier** [comment]
Hi !
Thanks for the answer !

Alas, I just have access to the Mustache templates, the rest is part of an app (mviewer). I'd rather not mess in their core code.

Would there be, by chance, a special tag that would allow to retrieve an entire object, serialized ? That might be quite handy and would solve my pb too

**Comment by jeanpommier** [comment]
Could even be {{.}}. When the current object is not a primitive, you get [object Object], which is not very useful. Why not display the serialized object then ?

**Comment by phillipj** [comment]
Yeah, the `[object Object]` you are seeing is the default `.toString()` of any object:

```js
$ node
> ({ 2019: { title: 'Twenty nineteen' } }).toString()
'[object Object]'
```

If one has control over the `Mustache.render()` call, it sounds doable to introduce some special kind of function that do JSON serialisation on values as shown in the section about [functions in README.md]( https://github.com/janl/mustache.js#functions).

I don't see us changing [our use of `String()`](https://github.com/janl/mustache.js/blob/master/mustache.mjs#L72)  (read: `.toString()`) on values to be the serialised version via `JSON.stringify()` instead if I understand you correctly.

**Comment by jeanpommier** [comment]
Oh, yeah, great hint, thanks a lot ! It seem neater than to serialize systematically as I planned to do. That's much more likely to pass as a PR to mviewer

Let's close the ticket then. Thanks for your help !
