### ISSUE TITLE
Return Partial from Lambda

### ISSUE THREAD

**Issue by Rabadash8820** [janl/mustache.js#746]
I recently came across the [epic debate about dynamic partials](https://github.com/mustache/spec/issues/54) in the Mustache spec repository. According to [one commenter](https://github.com/mustache/spec/issues/54#issuecomment-8651502), you should be able to achieve the effect of dynamic partials with code like below:

```
{
  items: [
    { url: 'Some URL',      html: function() { return '{{>image}}'; } },
    { content: 'Some text', html: function() { return '{{>text}}'; } },
  ]
}

base.mustache
{{#items}}
  {{{html}}}
{{/items}}

text.mustache
<p>{{content}}</p>

image.mustache
<p><img src="{{url}}"/></p>
```

Unfortunately, this code does not work for me, and `{{>image}}` and `{{>text}}` just show up in the final render. Is this a bug in mustache.js?

**Comment by Romanx** [comment]
If I remember correctly musache.js doesn't auto interpolate results and instead provides you with a render function to perform this yourself in lambda functions. I think it also has to be a section tag. Something like this:
```js
{
  "name": "Tater",
  "bold": function () {
    return function (text, render) {
      return "<b>" + render(text) + "</b>";
    }
  }
}

{{#bold}}Hi {{name}}.{{/bold}}
```

**Comment by Rabadash8820** [comment]
@Romanx Thanks for the quick response! And yes, looks like you were right on both counts, I needed to call `render` in the lambda and use a `{{#section}}` in the template. The fact that a lambda has to be a function that returns a function is completely beyond me...but if it works, whatev 🤷‍♂
