### ISSUE TITLE
Block helpers do not support using a helper as the target for the passed parameter

### ISSUE THREAD

**Issue by tonyobanon** [janl/mustache.js#750]
This does not work

<img width="1159" alt="Handlebars 2020-04-08 12-16-51" src="https://user-images.githubusercontent.com/12859467/78778358-0ccaeb80-7993-11ea-99cb-10acbfd0090f.png">

**Comment by phillipj** [comment]
Hi there!

At first glance it seems the examples are using handlebars.js, not
mustache.js that this repository is related to.

Should this issue have been opened in handlebar.js' repository instead?

**Comment by tonyobanon** [comment]
I totally missed this. My apologies

**Comment by phillipj** [comment]
No worries, thx for closing 👍
