### ISSUE TITLE
Bug: wrong documentation or multiple YAML documents not leadinng to multiple rendering

### ISSUE THREAD

**Issue by Kixunil** [janl/mustache.js#752]
According to man page:

```
If you provide multiple YAML documents (as delimited by ---), your template will be rendered multiple times. Like a  mail merge.
```

However, when actually tried on this template:

```mustache
location {{{root_path}}} {
	proxy_pass http://localhost:{{port}};
	proxy_http_version 1.1;
	proxy_set_header Host $http_host;
	proxy_set_header X-Forwarded-Proto $scheme;
	proxy_set_header X-Real-IP $remote_addr;
	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	proxy_set_header Upgrade $http_upgrade;
}
```

with this input YAML:

```yaml
---
port: 23000
root_path: "/btcpay"
---
port: 3000
root_path: "/rtl"
---
```

it produces:

```nginx
location /rtl {
	proxy_pass http://localhost:3000;
	proxy_http_version 1.1;
	proxy_set_header Host $http_host;
	proxy_set_header X-Forwarded-Proto $scheme;
	proxy_set_header X-Real-IP $remote_addr;
	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	proxy_set_header Upgrade $http_upgrade;
}
```

expected result:

```nginx
location /btcpay {
	proxy_pass http://localhost:23000;
	proxy_http_version 1.1;
	proxy_set_header Host $http_host;
	proxy_set_header X-Forwarded-Proto $scheme;
	proxy_set_header X-Real-IP $remote_addr;
	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	proxy_set_header Upgrade $http_upgrade;
}

location /rtl {
	proxy_pass http://localhost:3000;
	proxy_http_version 1.1;
	proxy_set_header Host $http_host;
	proxy_set_header X-Forwarded-Proto $scheme;
	proxy_set_header X-Real-IP $remote_addr;
	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	proxy_set_header Upgrade $http_upgrade;
}
```

I'm completely fine if you happen to not provide this feature anymore, just please fix the docs. I spent an insane amount of time debugging my config until I figured out `mustache` is broken.

Mustache version: 1.0.2

**Comment by Kixunil** [comment]
WTF, I accidentally reported against the wrong repository and this issue was even reported https://github.com/mustache/mustache/issues/254

Sorry about that.

**Comment by phillipj** [comment]
Hi there @Kixunil!

No worries, fully understand the confusion. Maybe not ideal for this JavaScript implementation to follow the mustache spec when it's used as a library, whilst not following the "spec" for the command line tool.

Let me know if you got a hunch what could have made you realise the difference between the command line tools earlier. Wouldn't surprise me if this has confused others out there as well.

**Comment by Kixunil** [comment]
Thanks, I wasn't using mustache.js at all, just installed `ruby-mustache` from Debian repository and when I figured out it doesn't work according to *their* documentation. I put "mustache" to Google and filed against the first github repo, not noticing that this is not ruby version. If I paid more attention, I would notice, I think.
