### ISSUE TITLE
Possible cache key collision

### ISSUE THREAD

**Issue by abacabadabacaba** [janl/mustache.js#762]
Currently, cache keys are computing this way:
```javascript
var cacheKey = template + ':' + (tags || mustache.tags).join(':');
```
If `tags` may include `:` characters, it is possible that different combinations of `template` and `tags` result in an identical `cacheKey`.

**Comment by phillipj** [comment]
Sorry for the late reply @abacabadabacaba.

You might surely be onto something we haven't taken into consideration. Please pushing a PR with a failing test case or a concrete example in this issue with the mustache template and view that makes it easy for anyone to reproduce.

**Comment by phillipj** [comment]
Closing this for now as there were no response from the issue author.
