### ISSUE TITLE
 [Angular Error]: TemplateSpans circularly references itself

### ISSUE THREAD

**Issue by soscler** [janl/mustache.js#763]
How to solve this error that I get when I use mustache in angular
ERROR in node_modules/@types/mustache/index.d.ts(362,6): error TS2456: Type alias 'TemplateSpans' circularly references itself.

I have the following versions:

Angular: 8.2.14
Mustache: 4.0.1
@types/mustache: 4.0.1
typescript: 3.5.3

**Comment by soscler** [comment]
One work arround is to use @ts-ignore, but this doesn't solve the issue, instead it hides it.
Another way is to remove the circular dependency inside the index.ts file but, I ignore what other bug I'll introduce by doing so.

**Comment by phillipj** [comment]
Hi @sioscler!

I seem to remember TypeScript adding support for circular references at some point, and the [`@types/mustache.js`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/6dd7b4f116aea7e614a1d43728859934f53f034c/types/mustache/index.d.ts#L8) declarations has this hint:

```ts
// Minimum TypeScript Version: 3.7
```

Try bumping your TypeScript version?

**Comment by soscler** [comment]
Thank you, upgrading to typescript 3.7.2 solved the issue.

**Comment by phillipj** [comment]
Yeay, thanks for the update 👍
