### ISSUE TITLE
Problem with creating pivot table 

### ISSUE THREAD

**Issue by AshishTondare175** [janl/mustache.js#769]

**Comment by phillipj** [comment]
Hi there!

It's hard to help you without *any* information what you've tried doing already.

From a distance, I'd expect it to be tricky to render `null` as a string like the desired output you've shown, but one trick you could try is to use changed `null`s into string's that contains `"null"` like this recent workaround shows: https://github.com/janl/mustache.js/issues/766#issuecomment-723865901
