### ISSUE TITLE
to_html replacement

### ISSUE THREAD

**Issue by mordechaihorowitz** [janl/mustache.js#771]
Doing a much overdue upgrade from mustache 0.7.  Having a bug because the code I inherited uses the deprecated to_html.  I don't see anything in the documentation that gives direction on replacing in old code except a mention very few projects will break because of it .  I have tried just replacing it with render and sometimes it breaks  Any direction would be helpful.

**Comment by phillipj** [comment]
Hi @mordechaihorowitz!

I see you're totally right about not finding any *concrete* examples how `to_html()` would be replaced in using projects. Very sorry about that.

Here's the implementation of `to_html()` in v3.x and below of mustache.js:

https://github.com/janl/mustache.js/blob/8e52a4ac6cf4ed86d0fedb3c4dae643fd7b56998/mustache.mjs#L696-L706

Mind sharing what your project are doing in practise? Most interestingly which one of these two:

#### 1. Passing a function to `to_html()`

```js
mustache.to_html(template, view, partials, (renderedResult) => {
  // do something with `renderedResult` here
})
```

If it still needs to work like this, your project would have to create a replacement that behaves similarly yourselves, e.g:

```js
function to_html (template, view, partials, send) {
  send(mustache.render(template, view, partials))
}
```

#### 2. Using the return value from `to_html()`

```js
const renderedResult = mustache.to_html(template, view, partials)
// do something with `renderedResult` here
```

If so, `mustache.render()` is a direct replacement for the old `mustache.to_html()` function.

**Comment by phillipj** [comment]
Closing this for now, don't hesitate to shout if you still got questions.
