### ISSUE TITLE
Please consider remove the -p flag!

### ISSUE THREAD

**Issue by d892fc** [janl/mustache.js#774]
> If your templates use partials you should pass paths to partials using -p flag:

This is very much inconvenient, could you please add a feature that kill the -p flag? Please?

**Comment by phillipj** [comment]
His there!

Would you be so kind and elaborate why that argument is so inconvent?

**Comment by d892fc** [comment]
@phillipj
Thanks very much for your attention! 

The situation is if a mustache template use partials, I have to pass paths to partials using -p flag, like this:

```
$ mustache -p path/to/partial1.mustache -p path/to/partial2.mustache dataView.json myTemplate.mustache
```

This is inconvenient because sometimes it's difficult to figure out what partials I've used in a template, what is worse is that even I have figured out that, I have to input a lot of words in the Terminal, it's very painful.

So I think there might be some way to not let a user to provide such information, because mustache.js can figure out them automatically:

```
-p path/to/partial1.mustache -p path/to/partial2.mustache
```

**Comment by d892fc** [comment]
@phillipj
Thanks very much for your attention! 

The situation is if a mustache template use partials, I have to pass paths to partials using -p flag, like this:

```
$ mustache -p path/to/partial1.mustache -p path/to/partial2.mustache dataView.json myTemplate.mustache
```

This is inconvenient because sometimes it's difficult to figure out what partials I've used in a template, what is worse is that even I have figured out that, I have to input a lot of words in the Terminal, it's very painful.

So I think there might be some way to not let a user to provide such information, because mustache.js can figure out them automatically:

```
-p path/to/partial1.mustache -p path/to/partial2.mustache
```

**Comment by phillipj** [comment]
I see your point of having to provide potentially many partial arguments.

It would be interesting to hear what & how you would have expected mustache.js to know where partials are located.

**Comment by d892fc** [comment]
The fact is I don't know, and that's why I asked for your help!

**Comment by phillipj** [comment]
Ahh okey.

I can personally imagine this behaving in lots of different ways. The obvious factors would be folder structure, filenames and extensions. Those will vary from project to project, and what would work for the majority of projects isn't obvious until we've got insights from many projects.

With that in mind, I'm very hesitant implementing anything into mustache.js itself. At least until we've got more use cases at hand. And removing the `-p` argument from the command line tool we've got wouldn't help much as far as I'm concerned.

**But**, the above does not mean we can't help you. There's usually several ways to solve a challenge. More concrete details about what you're facing would be helpful tho..

1. Are you able to run commands like `$ node a-custom-script-using-mustache.js` in your environment? Or are you strictly enforced to use the `mustache` executable?
2. How does your folder structure & filenames look like?

**Comment by d892fc** [comment]
Jan, thank you very much for your reply!

1. I'm sure that I will use the command line interface rather than custom JavaScript scripts to compile our templates, and we are certain to use mustache.js rather than any other language implementation of {{ mustache }}.

2. We don't use partials from node_mosules/ directories for now, our partials are either relative path to current template or use absolute paths.

The file extension is either .html or .mustache, we prefer .html because I think that mustache is only a useful syntax extension of HTML.


-------- 原始邮件 --------
发件人： Phillip Johnsen ***@***.***>
日期： 2021年3月29日周一 19:48
收件人： "janl/mustache.js" ***@***.***>
抄送： d892fc ***@***.***>, Author ***@***.***>
主 题： Re: [janl/mustache.js] Please consider remove the -p flag! (#774)

Ahh okey.

I can personally imagine this behaving in lots of different ways. The obvious factors would be folder structure, filenames and extensions. Those will vary from project to project, and what would work for the majority of projects isn't obvious until we've got insights from many projects.

With that in mind, I'm very hesitant implementing anything into mustache.js itself. At least until we've got more use cases at hand. And removing the -p argument from the command line tool we've got wouldn't help much as far as I'm concerned.

But, the above does not mean we can't help you. There's usually several ways to solve a challenge. More concrete details about what you're facing would be helpful tho..

  1.  Are you able to run commands like $ node a-custom-script-using-mustache.js in your environment? Or are you strictly enforced to use the mustache executable?
  2.  How does your folder structure & filenames look like?

―

**Comment by phillipj** [comment]
Thanks for sharing!

A custom .js script could do what you're looking for in many different ways, without being overly complex. Let me know if you'd reconsider using such a .js script that you'd be in total control of ofcourse, rather than the mustache executable directly.

**Comment by d892fc** [comment]
Janl, you are right.

But I still prefer using the executable, because it is easier to use for us.






-------- 原始邮件 --------
发件人： Phillip Johnsen ***@***.***>
日期： 2021年3月31日周三 04:14
收件人： "janl/mustache.js" ***@***.***>
抄送： d892fc ***@***.***>, Author ***@***.***>
主 题： Re: [janl/mustache.js] Please consider remove the -p flag! (#774)

Thanks for sharing!

A custom .js script could do what you're looking for in many different ways, without being overly complex. Let me know if you'd reconsider using such a .js script that you'd be in total control of ofcourse, rather than the mustache executable directly.

―

**Comment by d892fc** [comment]
A custom script is acceptable, but not my choice.

The logic is actuall analysis the {{> too/bar/baz }} directives, and find out where they are located.

We don't have to remove the -p command line flag, we can just ignore its values.




-------- 原始邮件 --------
发件人： Phillip Johnsen ***@***.***>
日期： 2021年3月31日周三 04:14
收件人： "janl/mustache.js" ***@***.***>
抄送： d892fc ***@***.***>, Author ***@***.***>
主 题： Re: [janl/mustache.js] Please consider remove the -p flag! (#774)

Thanks for sharing!

A custom .js script could do what you're looking for in many different ways, without being overly complex. Let me know if you'd reconsider using such a .js script that you'd be in total control of ofcourse, rather than the mustache executable directly.

―

**Comment by d892fc** [comment]
While, it is not a must to implement the enhanced version of the mustache executable.

We found a third solution to this. A web compiler normally has there parts, a checker, a complier and a minifier.

For example, rollup.js compiler has rollup-plugin-eslint to integrate ESLint, rollup-plugin-terser to integrate terser.

At the end, we found PostHTML like rollup.js  has a simple plugin named as post html-plugin-include can do the job.  So we don't need mustache executable to implement the feature we have been talking about.

The mian reason is, for now, I only need the partial including feature of mustache, I like mustache's syntax style, it's simply and looks handsome.

We use two temple engines in our project, one for temple designing, the other for use in HTTP request handlers.  The designer gives bundles of HTML temples, not a lot of partials.


-------- 原始邮件 --------
发件人： Phillip Johnsen ***@***.***>
日期： 2021年3月31日周三 04:14
收件人： "janl/mustache.js" ***@***.***>
抄送： d892fc ***@***.***>, Author ***@***.***>
主 题： Re: [janl/mustache.js] Please consider remove the -p flag! (#774)

Thanks for sharing!

A custom .js script could do what you're looking for in many different ways, without being overly complex. Let me know if you'd reconsider using such a .js script that you'd be in total control of ofcourse, rather than the mustache executable directly.

―

**Comment by phillipj** [comment]
> We found a third solution to this.

Great to hear you found something that suites your needs!

Handlebars.js has also been a great alternative for those who like mustache, but wants more opportunities.

I'm closing this issue for now, although for those who stumble upon this issue later and would like something similar, share your thoughts as feedback and other concrete use cases is a requirement for make this happen in mustache.js itself.

**Comment by d892fc** [comment]
I like mustache more, handlebars is too heavy.
