### ISSUE TITLE
need help, it only show when array contains at least one item

### ISSUE THREAD

**Issue by diveDylan** [janl/mustache.js#781]
```mustach
{{#query}}
query: {
      {{#query}}
        {{name}},
      {{/query}}
},
{{/query}}

```

expected when empty array, got nothing

```js
// not empty
query: {
  type,
   id
}

```

**Comment by phillipj** [comment]
Hi there!

You have to share more details about what you're doing in practise, especially how the data you're providing looks like.

**Comment by diveDylan** [comment]
> Hi there!
> 
> You have to share more details about what you're doing in practise, especially how the data you're providing looks like.

ooh. Maybe it's more clear
``` mustache
// my mustache
request(url, {
  method: 'get',
 // show query only when querys contains at least one items
 {{#querys}}
 query: {
    {{.}}
 },
{{/querys}}
})

```
when querys is `['type', 'id']`, just render as below
```js
request(url, {
   method: 'get',
   query: {
    type,
    id
  },
})
```
when query is empth, just render 
```js
request(url, {
   method: 'get',
})

```

**Comment by phillipj** [comment]
Here's a couple of tricks I could think of:

#### 1. Make `queryes` a plain string

```
const mustache = require('mustache');

const template = `
request(url, {
  method: 'get',
  {{#querys}}
  query: {
    {{.}}
  },
  {{/querys}}
})

mustache.render(template, {
  querys: 'type, id'
});
```

#### 2. Allow `request.query` to be an empty object

As usually an empty array with query parameters would yield the same result as not providing anything as query parameters.

```
const mustache = require('mustache');

const template = `
request(url, {
  method: 'get',
  query: {
  {{#querys}}
    {{.}},
  {{/querys}}
  },
})

mustache.render(template, {
  querys: ['type', 'id']
});
```

Hope that helps you get some ideas.

Closing this issue for now, it you'd like more creative ideas, I suggest heading to StackOverflow.
