### ISSUE TITLE
Mustache should not replace undefined value

### ISSUE THREAD

**Issue by ArvindhMangoleap** [janl/mustache.js#788]
```
var view = {
  name: "Joe",
};

var output = Mustache.render("{{title}} spends {{calc}}", view);
```
Give the following result
`Joe spends `

But what I desire is 
`Joe spends {{calc}}`

Mustache should not replace if the value is undefined.  Is there any way to achieve this?

**Comment by nbelyh** [comment]
Looks like you are looking for template validation. Have a look at this one: https://github.com/janl/mustache.js/issues/599

**Comment by phillipj** [comment]
@ArvindhMangoleap I cannot think of ways to do this out of the box, no.
