### ISSUE TITLE
Unexpected Token 'export'

### ISSUE THREAD

**Issue by KiddoV** [janl/mustache.js#796]
I got this issue in console when using the CDN: [mustache.js](https://cdnjs.cloudflare.com/ajax/libs/mustache.js/4.2.0/mustache.js)
Error in console:
```console
Uncaught SyntaxError: Unexpected token 'export' (at mustache.js:764:1)
```

**Spec:**

- OS: Windows 10
- Browser: Webview2 (Edge)
- MustacheJS: v4.2.0

Any idea why?
Thanks,

**Comment by phillipj** [comment]
Hi!

Cloudflare does not use the npm package, but rather serves the source code as is from github.com. After we made the source code into EcmaScript syntax, serving that as is for browser which doesn't support EcmaScript modules yet, wont work.

You could try serving from another CDN which does in fact use the npm package instead, in an "intended use scenario" so to speak. From the README example: [unpkg.com/mustache@latest](https://unpkg.com/mustache@latest), version pinning is also support by unpkg.com if you'd prefer that..

**Comment by KiddoV** [comment]
@phillipj Thanks this [https://unpkg.com/mustache@4.2.0/mustache.js](https://unpkg.com/mustache@4.2.0/mustache.js) works for me!

**Comment by gtraxx** [comment]
> Hi!
> 
> Cloudflare does not use the npm package, but rather serves the source code as is from github.com. After we made the source code into EcmaScript syntax, serving that as is for browser which doesn't support EcmaScript modules yet, wont work.
> 
> You could try serving from another CDN which does in fact use the npm package instead, in an "intended use scenario" so to speak. From the README example: [unpkg.com/mustache@latest](https://unpkg.com/mustache@latest), version pinning is also support by unpkg.com if you'd prefer that..

Hi, Can we convert the file to match the one on https://unpkg.com/mustache@latest
I guess we can do this with node ?

Best Regards
