### ISSUE TITLE
How to prevent mustache from encoding the url value?

### ISSUE THREAD

**Issue by fzn0x** [janl/mustache.js#806]
How to prevent mustache from encoding the url value?

```js
const stringDoc = Mustache.render("This is your {{ endpoint }}", {
  endpoint: "https://loli.dev",
});
console.log(stringDoc); // https:&#x2F;&#x2F;loli.dev
```

## Expected value
This is your https://loli.dev

**Comment by fzn0x** [comment]
Decoding the result solve my issue, if it's still the part of the mustache issue, you can reopen it.

```js
stringDoc = stringDoc.replace(REG_HEX, function (match, group) {
  var num = parseInt(group, 16); //=> 39
  return String.fromCharCode(num); //=> '
});

consol.log(stringDoc);
```

Happy hacking!

**Comment by phillipj** [comment]
```
This is your {{{ endpoint }}}
```

Was not an option to avoid HTML escaping completely?

**Comment by fzn0x** [comment]
> ```
> This is your {{{ endpoint }}}
> ```
> 
> Was not an option to avoid HTML escaping completely?

I don't see that is return the expected value, the slashes there has the `&#x2F;&#x2F;` output.

**Comment by fzn0x** [comment]
> ```
> This is your {{{ endpoint }}}
> ```
> 
> Was not an option to avoid HTML escaping completely?

Wow, you are right haha. I missed that part in the docs! 😄

**Comment by fzn0x** [comment]
Thank you!

**Comment by phillipj** [comment]
No worries, I'd say it's yet another hint to improve docs 😬

You're certainly not the first one who's asked and been surprised the
built-in HTML encoding can be avoided when needed.
