### ISSUE TITLE
Selectbox and mustache

### ISSUE THREAD

**Issue by bernhardh** [janl/mustache.js#82]
Hello,

how can I use mustache to set an option of a selectbox to selected?

For example:

< select name="test">
< option value="1">1</option>
< option value="2">2</option>
< option value="3">3</option>
< /select>

The corresponding variable would be {{selectedEntry}}.
But how can I set the correct option to selected, without using JS on the client side?

**Comment by ezekielarin** [comment]
is there a way to create a modal in same mustachejs template

**Comment by phillipj** [comment]
@ezekielarin mustache.js can't do modals on its own.

mustache.js can only create/render the contents (HTML) needed for a modal. The other part that's usually involved for modals, is the code that adds behaviour to the modal, like reacting to the visitor clicking a link or button. That part has to be done by a JavaScript click listener.
